function tests = test_trkg4_green_fingerprint
%TEST_TRKG4_GREEN_FINGERPRINT Behavioral tests for the Green-cache payload hash.
tests = functiontests(localfunctions);
end

function setupOnce(test_case)
project_root = fileparts(fileparts(mfilename('fullpath')));
addpath(fullfile(project_root, 'src'));
test_case.TestData.project_root = project_root;
end

function testEqualPayloadIsStableAcrossNumericTypesAndFieldOrder(test_case)
[fmdl, sigma, candidate_nodes, settings] = local_fixture();
expected = trkg4_green_fingerprint( ...
    fmdl, sigma, candidate_nodes, settings);

typed = fmdl;
typed.nodes = single(typed.nodes);
typed.elems = uint32(typed.elems);
typed.boundary = uint32(typed.boundary);
typed.gnd_node = uint32(typed.gnd_node);
typed_settings = struct( ...
    'nested', struct('beta', single(2), 'alpha', single(1)), ...
    'mode', "unit", ...
    'block_size', single(64), ...
    'contact_impedance_ohm_m2', single(0.000244140625));
actual = trkg4_green_fingerprint( ...
    typed, single(sigma), uint32(candidate_nodes), typed_settings);

verifyEqual(test_case, actual, expected);
verifyEqual(test_case, numel(actual), 64);
end

function testEveryPhysicalPayloadChangeChangesFingerprint(test_case)
[fmdl, sigma, candidate_nodes, settings] = local_fixture();
baseline = trkg4_green_fingerprint( ...
    fmdl, sigma, candidate_nodes, settings);

changed = fmdl;
changed.nodes(1, 1) = changed.nodes(1, 1) + 1e-3;
local_verify_changed(test_case, baseline, ...
    trkg4_green_fingerprint(changed, sigma, candidate_nodes, settings), ...
    'coordinates');

changed = fmdl;
changed.elems(1, [1 2]) = changed.elems(1, [2 1]);
local_verify_changed(test_case, baseline, ...
    trkg4_green_fingerprint(changed, sigma, candidate_nodes, settings), ...
    'connectivity');

changed_sigma = sigma;
changed_sigma(3) = changed_sigma(3) * 1.1; % element assigned to bone
local_verify_changed(test_case, baseline, ...
    trkg4_green_fingerprint(fmdl, changed_sigma, candidate_nodes, settings), ...
    'bone conductivity');

changed = fmdl;
changed.gnd_node = 2;
local_verify_changed(test_case, baseline, ...
    trkg4_green_fingerprint(changed, sigma, candidate_nodes, settings), ...
    'ground node');

changed_candidates = [2; 4; 5];
local_verify_changed(test_case, baseline, ...
    trkg4_green_fingerprint(fmdl, sigma, changed_candidates, settings), ...
    'candidate nodes');

changed_settings = settings;
changed_settings.block_size = settings.block_size + 1;
local_verify_changed(test_case, baseline, ...
    trkg4_green_fingerprint(fmdl, sigma, candidate_nodes, changed_settings), ...
    'operator settings');

changed = fmdl;
changed.system_mat(1, 1) = changed.system_mat(1, 1) + 0.5;
local_verify_changed(test_case, baseline, ...
    trkg4_green_fingerprint(changed, sigma, candidate_nodes, settings), ...
    'system matrix context');

changed = fmdl;
changed.approx_type = 'alternative';
local_verify_changed(test_case, baseline, ...
    trkg4_green_fingerprint(changed, sigma, candidate_nodes, settings), ...
    'approximation context');
end

function local_verify_changed(test_case, baseline, changed, label)
verifyFalse(test_case, strcmp(baseline, changed), ...
    sprintf('Fingerprint did not change for %s.', label));
end

function [fmdl, sigma, candidate_nodes, settings] = local_fixture
fmdl = struct( ...
    'nodes', [ ...
        0 0 0;
        1 0 0;
        0 1 0;
        0 0 1;
        1 1 1], ...
    'elems', [1 2 3 4; 2 3 4 5], ...
    'boundary', [1 2 3; 1 2 4], ...
    'gnd_node', 1, ...
    'system_mat', sparse([2 -1; -1 2]), ...
    'approx_type', 'standard');
sigma = [0.25; 0.125; 0.0078125];
candidate_nodes = [2; 3; 5];
settings = struct( ...
    'mode', 'unit', ...
    'block_size', 64, ...
    'contact_impedance_ohm_m2', 0.000244140625, ...
    'nested', struct('beta', 2, 'alpha', 1));
end
