function tests = test_trkg4_load_surface_landmarks
%TEST_TRKG4_LOAD_SURFACE_LANDMARKS Tests for the JSON landmark loader.

    tests = functiontests(localfunctions);
end

function setupOnce(test_case)
    source_directory = fullfile( ...
        fileparts(fileparts(mfilename('fullpath'))), 'src');
    path_entries = strsplit(path, pathsep);
    source_was_on_path = any(strcmpi(path_entries, source_directory));
    if ~source_was_on_path
        addpath(source_directory);
    end
    test_case.TestData.source_directory = source_directory;
    test_case.TestData.source_added_by_test = ~source_was_on_path;
end

function teardownOnce(test_case)
    if test_case.TestData.source_added_by_test
        rmpath(test_case.TestData.source_directory);
    end
end

function testValidJsonReturnsCanonicalDoubleMatrices(test_case)
    payload = localValidPayload();
    payload.untrusted_metadata = struct('absolute_path', 'D:\private\scan');
    json_file = localWriteJson(test_case, jsonencode(payload));

    landmarks = trkg4_load_surface_landmarks(json_file);

    verifyClass(test_case, landmarks.right_guide_points_xyz_mm, 'double');
    verifyClass(test_case, landmarks.left_guide_points_xyz_mm, 'double');
    verifySize(test_case, landmarks.right_guide_points_xyz_mm, [2 3]);
    verifySize(test_case, landmarks.left_guide_points_xyz_mm, [3 3]);
    verifyEqual(test_case, landmarks.coordinate_system, 'surface_path_v1');
    verifyEqual(test_case, landmarks.units, 'mm');
    verifyEqual(test_case, landmarks.source_basename, 'body_surface.stl');
    verifyFalse(test_case, isfield(landmarks, 'untrusted_metadata'));
    verifyEqual(test_case, landmarks.right_guide_points_xyz_mm, ...
        [1 2 3; 4 5 6]);
end

function testTtrkgSymmetricContractIsValidatedAndPreserved(test_case)
    payload = localValidPayload();
    payload.schema = 'trkg4_ttrkg_arm_surface_v2';
    payload.modality = 'TTRKG';
    payload.montage = 'four_electrode_arm_surface';
    payload.reference_definition = ...
        'first_resolved_guide_point_at_arm_trunk_boundary_proximal_to_distal';
    payload.electrode_order = ...
        {'I_plus', 'V_plus', 'V_minus', 'I_minus'};
    payload.symmetry = struct('mode', 'equal_path_distances', ...
        'inner_from_reference_mm', 20, 'outer_from_inner_mm', 80);
    json_file = localWriteJson(test_case, jsonencode(payload));

    landmarks = trkg4_load_surface_landmarks(json_file);

    verifyEqual(test_case, landmarks.schema, 'trkg4_ttrkg_arm_surface_v2');
    verifyEqual(test_case, landmarks.modality, 'TTRKG');
    verifyEqual(test_case, landmarks.montage, 'four_electrode_arm_surface');
    verifyEqual(test_case, landmarks.electrode_order, ...
        ["I_plus"; "V_plus"; "V_minus"; "I_minus"]);
    verifyEqual(test_case, landmarks.symmetry.mode, 'equal_path_distances');
    verifyEqual(test_case, landmarks.symmetry.inner_from_reference_mm, 20);
    verifyEqual(test_case, landmarks.symmetry.outer_from_inner_mm, 80);
end

function testInvalidTtrkgSymmetryIsRejected(test_case)
    payload = localValidPayload();
    payload.schema = 'trkg4_ttrkg_arm_surface_v2';
    payload.modality = 'TTRKG';
    payload.montage = 'four_electrode_arm_surface';
    payload.reference_definition = ...
        'first_resolved_guide_point_at_arm_trunk_boundary_proximal_to_distal';
    payload.electrode_order = ...
        {'I_plus', 'V_plus', 'V_minus', 'I_minus'};
    payload.symmetry = struct('mode', 'mirror_xyz', ...
        'inner_from_reference_mm', 20, 'outer_from_inner_mm', 80);
    json_file = localWriteJson(test_case, jsonencode(payload));

    verifyError(test_case, @() trkg4_load_surface_landmarks(json_file), ...
        'trkg4:load_surface_landmarks:InvalidTtrkgSymmetry');
end

function testZeroOuterDistanceIsRejected(test_case)
    payload = localValidPayload();
    payload.schema = 'trkg4_ttrkg_arm_surface_v2';
    payload.modality = 'TTRKG';
    payload.montage = 'four_electrode_arm_surface';
    payload.reference_definition = ...
        'first_resolved_guide_point_at_arm_trunk_boundary_proximal_to_distal';
    payload.electrode_order = ...
        {'I_plus', 'V_plus', 'V_minus', 'I_minus'};
    payload.symmetry = struct('mode', 'equal_path_distances', ...
        'inner_from_reference_mm', 20, 'outer_from_inner_mm', 0);
    json_file = localWriteJson(test_case, jsonencode(payload));

    verifyError(test_case, @() trkg4_load_surface_landmarks(json_file), ...
        'trkg4:load_surface_landmarks:InvalidTtrkgSymmetry');
end

function testInsufficientPointsIsRejected(test_case)
    payload = localValidPayload();
    payload.right_guide_points_xyz_mm = [1 2 3];
    json_file = localWriteJson(test_case, jsonencode(payload));

    verifyError(test_case, ...
        @() trkg4_load_surface_landmarks(json_file), ...
        'trkg4:load_surface_landmarks:InvalidGuidePoints');
end

function testCoordinateSystemAndUnitsAreChecked(test_case)
    payload = localValidPayload();
    payload.coordinate_system = 'other_coordinate_system';
    json_file = localWriteJson(test_case, jsonencode(payload));
    verifyError(test_case, ...
        @() trkg4_load_surface_landmarks(json_file), ...
        'trkg4:load_surface_landmarks:InvalidCoordinateSystem');

    payload = localValidPayload();
    payload.units = 'ohm_m';
    json_file = localWriteJson(test_case, jsonencode(payload));
    verifyError(test_case, ...
        @() trkg4_load_surface_landmarks(json_file), ...
        'trkg4:load_surface_landmarks:InvalidUnits');
end

function testAbsoluteAndNestedSourceBasenamesAreRejected(test_case)
    invalid_names = {'C:\data\body_surface.stl', 'folder/body_surface.stl'};
    for name_index = 1:numel(invalid_names)
        payload = localValidPayload();
        payload.source_basename = invalid_names{name_index};
        json_file = localWriteJson(test_case, jsonencode(payload));
        verifyError(test_case, ...
            @() trkg4_load_surface_landmarks(json_file), ...
            'trkg4:load_surface_landmarks:InvalidSourceBasename');
    end
end

function testNaNCoordinateIsRejected(test_case)
    json_text = localJsonWithPoints( ...
        '[[1, 2, null], [4, 5, 6]]', ...
        '[[7, 8, 9], [10, 11, 12]]');
    json_file = localWriteJson(test_case, json_text);

    verifyError(test_case, ...
        @() trkg4_load_surface_landmarks(json_file), ...
        'trkg4:load_surface_landmarks:InvalidGuidePoints');
end

function testNonNumericCoordinateIsRejected(test_case)
    json_text = localJsonWithPoints( ...
        '[[1, 2, "not-a-number"], [4, 5, 6]]', ...
        '[[7, 8, 9], [10, 11, 12]]');
    json_file = localWriteJson(test_case, json_text);

    verifyError(test_case, ...
        @() trkg4_load_surface_landmarks(json_file), ...
        'trkg4:load_surface_landmarks:InvalidGuidePoints');
end

function testGenericSurfaceContractUsesArbitrarySurfaceGuides(test_case)
    payload = struct( ...
        'schema', 'trkg4_ttrkg_surface_v3', ...
        'modality', 'TTRKG', ...
        'montage', 'four_electrode_surface', ...
        'placement_mode', 'symmetric_paths', ...
        'coordinate_system', 'surface_path_v1', ...
        'units', 'mm', ...
        'source_basename', 'body_surface.stl', ...
        'reference_definition', ...
        'first_resolved_guide_point_at_user_selected_anatomical_reference', ...
        'electrode_order', ...
        {{'I_plus', 'V_plus', 'V_minus', 'I_minus'}}, ...
        'symmetry', struct('mode', 'equal_path_distances', ...
        'inner_from_reference_mm', 20, 'outer_from_inner_mm', 80), ...
        'positive_guide_points_xyz_mm', [1 2 3; 4 5 6], ...
        'negative_guide_points_xyz_mm', [7 8 9; 10 11 12]);
    json_file = localWriteJson(test_case, jsonencode(payload));

    landmarks = trkg4_load_surface_landmarks(json_file);

    verifyEqual(test_case, landmarks.schema, 'trkg4_ttrkg_surface_v3');
    verifyEqual(test_case, landmarks.montage, 'four_electrode_surface');
    verifyEqual(test_case, landmarks.placement_mode, 'symmetric_paths');
    verifyEqual(test_case, landmarks.positive_guide_points_xyz_mm, ...
        [1 2 3; 4 5 6]);
    verifyEqual(test_case, landmarks.negative_guide_points_xyz_mm, ...
        [7 8 9; 10 11 12]);
    verifyFalse(test_case, isfield(landmarks, ...
        'right_guide_points_xyz_mm'));
end

function testExplicitSurfaceContractReturnsRequestedCentres(test_case)
    centres = struct( ...
        'I_plus', [1 2 3], ...
        'V_plus', [4 5 6], ...
        'V_minus', [7 8 9], ...
        'I_minus', [10 11 12]);
    payload = struct( ...
        'schema', 'trkg4_ttrkg_surface_v3', ...
        'modality', 'TTRKG', ...
        'montage', 'four_electrode_surface', ...
        'placement_mode', 'explicit_points', ...
        'coordinate_system', 'surface_path_v1', ...
        'units', 'mm', ...
        'source_basename', 'body_surface.stl', ...
        'reference_definition', ...
        'user_selected_centres_on_external_body_surface', ...
        'electrode_order', ...
        {{'I_plus', 'V_plus', 'V_minus', 'I_minus'}}, ...
        'symmetry', [], ...
        'preliminary_electrode_centers_xyz_mm', centres);
    json_file = localWriteJson(test_case, jsonencode(payload));

    landmarks = trkg4_load_surface_landmarks(json_file);

    verifyEqual(test_case, landmarks.placement_mode, 'explicit_points');
    verifyEqual(test_case, landmarks.requested_centres_xyz_mm, ...
        [1 2 3; 4 5 6; 7 8 9; 10 11 12]);
    verifyEmpty(test_case, landmarks.symmetry);
    verifyFalse(test_case, isfield(landmarks, ...
        'positive_guide_points_xyz_mm'));
end

function testExplicitSurfaceContractRejectsMissingCentre(test_case)
    centres = struct( ...
        'I_plus', [1 2 3], ...
        'V_plus', [4 5 6], ...
        'V_minus', [7 8 9]);
    payload = struct( ...
        'schema', 'trkg4_ttrkg_surface_v3', ...
        'modality', 'TTRKG', ...
        'montage', 'four_electrode_surface', ...
        'placement_mode', 'explicit_points', ...
        'coordinate_system', 'surface_path_v1', ...
        'units', 'mm', ...
        'source_basename', 'body_surface.stl', ...
        'reference_definition', ...
        'user_selected_centres_on_external_body_surface', ...
        'electrode_order', ...
        {{'I_plus', 'V_plus', 'V_minus', 'I_minus'}}, ...
        'symmetry', [], ...
        'preliminary_electrode_centers_xyz_mm', centres);
    json_file = localWriteJson(test_case, jsonencode(payload));

    verifyError(test_case, @() trkg4_load_surface_landmarks(json_file), ...
        'trkg4:load_surface_landmarks:InvalidElectrodeCentres');
end

function payload = localValidPayload()
    payload = struct( ...
        'coordinate_system', 'surface_path_v1', ...
        'units', 'mm', ...
        'source_basename', 'body_surface.stl', ...
        'right_guide_points_xyz_mm', [1 2 3; 4 5 6], ...
        'left_guide_points_xyz_mm', [7 8 9; 10 11 12; 13 14 15]);
end

function json_text = localJsonWithPoints(right_points, left_points)
    json_text = ['{"coordinate_system":"surface_path_v1",' ...
        '"units":"mm",' ...
        '"source_basename":"body_surface.stl",' ...
        '"right_guide_points_xyz_mm":', right_points, ',' ...
        '"left_guide_points_xyz_mm":', left_points, '}'];
end

function json_file = localWriteJson(test_case, json_text)
    json_file = [tempname, '.json'];
    file_identifier = fopen(json_file, 'w', 'n', 'UTF-8');
    if file_identifier < 0
        error('test_trkg4_load_surface_landmarks:FileCreateFailed', ...
            'Не удалось создать временный JSON-файл.');
    end
    fwrite(file_identifier, json_text, 'char');
    fclose(file_identifier);
    addTeardown(test_case, @() localDeleteFile(json_file));
end

function localDeleteFile(json_file)
    if isfile(json_file)
        delete(json_file);
    end
end
