function cfg = trkg4_config(subject_id)
%TRKG4_CONFIG Configuration for 4-electrode real-subject TRKG modeling.

if nargin < 1 || isempty(subject_id)
    subject_id = 'nik';
end

cfg = struct();
cfg.project_root = fileparts(fileparts(mfilename('fullpath')));
cfg.src_dir = fullfile(cfg.project_root, 'src');
cfg.vendor_dir = fullfile(cfg.project_root, 'vendor_stl_eidors');
addpath(cfg.src_dir);
addpath(cfg.vendor_dir);

subjects = trkg4_subject_registry(cfg.project_root);
cfg.subject = trkg4_get_subject(subjects, subject_id);

cfg.input_mode = 'real_ct_stl_trkg4';
cfg.frequency_hz = 50e3;
cfg.itis_database = 'ITIS Tissue Properties Database V5.0';
cfg.eidors_startup = getenv('EIDORS_STARTUP');
cfg.gmsh_executable = getenv('GMSH_EXE');

% CT STL files are expected in millimetres. Tissue classification and
% electrode patch selection use mm; the FEM solve is scaled to metres.
cfg.length_unit = 'mm';
cfg.scale_nodes_to_si = true;

cfg.mesher = 'gmsh';       % gmsh or netgen, only used without a prebuilt mesh
cfg.gmsh_mesh_size = 25;   % in STL units, normally mm
cfg.mesh_fineness = 'moderate';

% Characteristic edge length of the mesh actually being solved. With a
% prebuilt mesh this is NOT cfg.gmsh_mesh_size: the accepted v5 mesh is
% built from a 1 mm surface and locally refined to 2 mm near the electrodes.
% Diagnostics tolerances are derived from this number, so it must be kept in
% step with cfg.prebuilt_mesh_file.
cfg.mesh_target_size_mm = 2;
cfg.show_figures = false;
cfg.use_parallel_assignment = true;
cfg.parallel_workers = 'auto';
cfg.reuse_mesh_cache = true;

cfg.n_electrodes = 4;
cfg.electrode_order = {'I_plus', 'V_plus', 'V_minus', 'I_minus'};
cfg.current_ampere = 1;
% Contact area of one electrode: a 10 mm disc, derated to 90% for the part of
% the gel pad that does not conduct. Since electrode_faces_by_area was fixed,
% this is the area of the INDUCED face set, i.e. the surface the complete
% electrode model integrates over. It used to be compared against the
% explicitly picked faces only, which made the real contact area larger than
% this number; impedances computed before that fix are not comparable.
cfg.electrode_area_mm2 = pi * 10^2 / 4 * 0.9;
cfg.electrode_area = cfg.electrode_area_mm2;
cfg.z_contact_ohm_m2 = 2.5e-7 * 0.05 / (pi * 0.01^2 / 4);
cfg.z_contact = cfg.z_contact_ohm_m2;
cfg.electrode_centres_xyz = [];
cfg.electrode_centres_file = cfg.subject.electrodes_csv;

% Move each requested centre onto the nearest boundary node before growing
% its patch. On the v5 surface the median edge is about 1.5 mm, so the shift
% is submillimetric, and it stops a centre that sits a few millimetres inside
% a thin limb from seeding a patch that wraps around both sides of the limb.
%
% Deliberately NOT applied in run_trkg4_inverse_inhale: there the centres are
% generated by projecting a fitted pose onto the skin, and the pose offsets
% are continuous fit parameters. Snapping would quantise them to the node
% spacing, turning the objective into a staircase and stalling the optimiser.
% The two conventions differ on purpose; see docs/ELECTRODES_4.md.
cfg.snap_electrode_centres_to_nodes = true;

% Electrode placement tolerances.
%
% These are scaled to the mesh actually being solved and to the electrode
% itself, not to cfg.gmsh_mesh_size. Tying them to the mesher parameter gave
% a 50 mm tolerance on a 2 mm mesh, which no realistic misplacement could
% ever exceed.
%
% patch_radius = sqrt(electrode_area / pi) is about 4.7 mm for the 10 mm disc
% used here. A centroid that drifts by more than one patch radius means the
% patch grew markedly to one side.
cfg.electrode_patch_radius_mm = sqrt(cfg.electrode_area_mm2 / pi);
cfg.max_electrode_surface_distance_mm = 5;
cfg.max_electrode_patch_centroid_offset_mm = cfg.electrode_patch_radius_mm;
cfg.min_electrode_patch_area_fraction = 0.95;
cfg.max_electrode_patch_area_ratio = 1.5;

% Placement problems change the current density under the electrode and
% therefore the reported Z. They must stop the run rather than scroll past in
% a warning. Set to false only for deliberate exploration of bad placements.
cfg.fail_on_electrode_diagnostics = true;
cfg.electrode_diagnostics_file = fullfile(cfg.project_root, 'output', ...
    sprintf('%s_electrode_diagnostics.csv', cfg.subject.id));

cfg.body_stl = cfg.subject.stl.body;
cfg.output_file = fullfile(cfg.project_root, 'output', ...
    sprintf('%s_trkg4_forward.mat', cfg.subject.id));
cfg.mesh_cache_file = fullfile(cfg.project_root, 'output', ...
    sprintf('%s_body_mesh_v5_1mm_local2mm_cache.mat', cfg.subject.id));
cfg.prebuilt_mesh_file = fullfile(cfg.project_root, 'output', ...
    'nik_body_solid_v3_1mm_local2mm_alg1.msh');

% Replace these by selected points from the solution clouds for each
% subject/state. Defaults are the current Nik investigation values.
cfg.rho_cloud.soft_ohm_m = 4.728174786010649;
cfg.rho_cloud.lungs_ohm_m = 17.4067;
cfg.rho_cloud.lungs_inhale_ohm_m = 17.73503700425868;
cfg.rho_cloud.source = ...
    'Nik solution clouds / historical MATLAB-Python model calculations';

sigma_soft = 1 / cfg.rho_cloud.soft_ohm_m;
sigma_lung = 1 / cfg.rho_cloud.lungs_ohm_m;
sigma_heart = itis_conductivity('Heart Muscle', cfg.frequency_hz);
sigma_bone = itis_conductivity('Bone (Cortical)', cfg.frequency_hz);
sigma_blood = itis_conductivity('Blood', cfg.frequency_hz);

cfg.background.name = 'soft_tissue';
cfg.background.itis_name = 'own_solution_cloud';
cfg.background.sigma = sigma_soft;

cfg.required_tissues = {'lungs', 'heart', 'bones'};
cfg.tissues = struct('name', {}, 'file', {}, 'itis_name', {}, 'sigma', {}, 'enabled', {});
cfg.tissues(end + 1) = local_tissue_entry('lungs', cfg.subject.stl.lungs, ...
    'own_solution_cloud', sigma_lung, true);
% Nik has a whole-heart mask, not separate myocardium and blood masks.
% Assigning Heart Muscle conductivity to the full mask is a modelling assumption.
cfg.tissues(end + 1) = local_tissue_entry('heart', cfg.subject.stl.heart, ...
    'Heart Muscle', sigma_heart, true);
cfg.tissues(end + 1) = local_tissue_entry('bones', cfg.subject.stl.bones, ...
    'Bone (Cortical)', sigma_bone, true);
cfg.tissues(end + 1) = local_tissue_entry('blood', cfg.subject.stl.blood, ...
    'Blood', sigma_blood, true);
end

function tissue = local_tissue_entry(name, file, itis_name, sigma, enabled)
tissue = struct( ...
    'name', name, ...
    'file', file, ...
    'itis_name', itis_name, ...
    'sigma', sigma, ...
    'enabled', enabled);
end
