function [centres_xyz_mm, diagnostics] = trkg4_surface_montage_centres( ...
    fmdl, positive_guide_points_xyz_mm, negative_guide_points_xyz_mm, ...
    inner_from_reference_mm, outer_from_inner_mm)
%TRKG4_SURFACE_MONTAGE_CENTRES Resolve a four-electrode TTRKG surface montage.
%
% The two guide paths may lie on any parts of the external body surface.
% Their first points are corresponding anatomical references chosen by the
% user. Scalar distances apply equally to both paths. The result order is
% I_plus, V_plus, V_minus, I_minus.

[centres_xyz_mm, legacy] = trkg4_arm_surface_centres( ...
    fmdl, positive_guide_points_xyz_mm, negative_guide_points_xyz_mm, ...
    inner_from_reference_mm, outer_from_inner_mm);

diagnostics = legacy;
diagnostics.reference_definition = ...
    "first resolved guide point at a user-selected anatomical reference";
diagnostics.positive_path = legacy.right_path;
diagnostics.negative_path = legacy.left_path;
diagnostics.positive_realised_separation_mm = ...
    legacy.right_realised_separation_mm;
diagnostics.negative_realised_separation_mm = ...
    legacy.left_realised_separation_mm;
diagnostics.centre_table.side = ...
    ["positive"; "positive"; "negative"; "negative"];
diagnostics = rmfield(diagnostics, { ...
    'right_path', 'left_path', ...
    'right_realised_separation_mm', ...
    'left_realised_separation_mm'});
end
