"""Assemble matched OLD candidates and diagnostic figures; never certifies anatomy.

Inputs remain local. Run after all transport and HU receipts are available:
python build_old_dynamic_comparison.py --root <OLD_ROOT> --output <NEW_OUTPUT>
"""
from pathlib import Path
import argparse,json
import nibabel as nib
import numpy as np
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
from compare_authored_cardiac_volumes import compare,sha,read_mask,CHAMBERS

NAMES={"LV":"Левый желудочек", "RV":"Правый желудочек", "LA":"Левое предсердие", "RA":"Правое предсердие"}
TS_NAMES={"LV":"heart_ventricle_left", "RV":"heart_ventricle_right", "LA":"heart_atrium_left", "RA":"heart_atrium_right"}
def read(p):return json.loads(Path(p).read_text(encoding="utf-8-sig"))
def write(p,x):Path(p).write_text(json.dumps(x,ensure_ascii=False,indent=2),encoding="utf-8")
def assemble(root,out,expected=20):
 root=Path(root).resolve();out=Path(out).resolve()
 if out.exists():raise FileExistsError(out)
 ts=root/"sequence02_ts_comparator_v1";state=read(ts/"status/run_status.json")
 receipts=sorted((root/"whole_heart_dynamic_hu_v01").glob("phase_*/receipt.json"))
 if len(receipts)!=expected:raise ValueError(f"Expected {expected} HU phases; found {len(receipts)}")
 phases=[];supp=[];thresholds=[];registration=[];spatial=[]
 for rp in receipts:
  r=read(rp)
  if sha(root/"whole_chamber_review_v01/phase00_search_domains_v01/chamber_domains.nii.gz")!=r["source_domains_sha256"]:raise ValueError("Source search domains changed")
  pid=r["phase_id"];ctpath=root/"sequence_02/phases"/(pid+".nii.gz")
  ct=nib.load(ctpath);v=abs(np.linalg.det(ct.affine[:3,:3]))/1000
  tp=root/"whole_heart_dynamic_v01"/pid/"receipt.json";t=read(tp)
  if sha(tp)!=r["transport_receipt_sha256"]:raise ValueError("Transport receipt changed")
  if t["source_ct_sha256"]!=r["source_ct_sha256"]:raise ValueError("Source mismatch")
  p=dict(phase_id=pid,phase_percent=r["phase_percent"],ct_path=str(ctpath),ct_sha256=r["source_ct_sha256"],
    authored_source_ct_sha256=r["source_ct_sha256"],automatic_source_ct_sha256=state["phase_input_hashes"][pid],
    authored_masks={},automatic_masks={},authored_mask_hashes={},automatic_mask_hashes={},
    authored_method=r["method"],reference_accepted=False,whole_chamber_confirmed=False)
  auto_arrays={};auth_arrays={}
  for ch in CHAMBERS:
   ap=rp.parent/f"{ch}_HU190.nii.gz";rel=f"automatic_masks_v2/{pid}/heartchambers_highres/{TS_NAMES[ch]}.nii.gz";mp=ts/rel
   p["authored_masks"][ch]=str(ap);p["automatic_masks"][ch]=str(mp)
   p["authored_mask_hashes"][ch]=r["records"][ch+"_HU190"]["sha256"]
   p["automatic_mask_hashes"][ch]=state["phase_hashes"][pid][rel]
   auth_arrays[ch]=read_mask(ap,ct);auto_arrays[ch]=read_mask(mp,ct)
   for hu in [170,190,210]:
    rec=r["records"][f"{ch}_HU{hu}"];path=rp.parent/rec["file"]
    if sha(path)!=rec["sha256"]:raise ValueError("HU mask changed")
    measured=float(read_mask(path,ct).sum()*v)
    if not np.isclose(measured,rec["volume_ml"],atol=1e-5,rtol=0):raise ValueError("Volume receipt mismatch")
    thresholds.append(dict(phase_id=pid,phase_percent=r["phase_percent"],region=ch,threshold_hu=hu,volume_ml=measured))
  for key,rec in t["records"].items():
   path=tp.parent/rec["file"]
   if sha(path)!=rec["sha256"]:raise ValueError("Transport mask changed")
   measured=float(read_mask(path,ct).sum()*v)
   supp.append(dict(phase_id=pid,phase_percent=r["phase_percent"],method="transport",region=key,volume_ml=measured))
  for key,rel in [("outer_heart_candidate",f"automatic_masks_v2/{pid}/total_heart/heart.nii.gz"),("myocardium_intensity_candidate",f"automatic_masks_v2/{pid}/heartchambers_highres/heart_myocardium.nii.gz")]:
   path=ts/rel
   if sha(path)!=state["phase_hashes"][pid][rel]:raise ValueError("TS supplemental mask changed")
   supp.append(dict(phase_id=pid,phase_percent=r["phase_percent"],method="TotalSegmentator",region=key,volume_ml=float(read_mask(path,ct).sum()*v)))
  rv=auth_arrays["RV"];trv=auto_arrays["RV"];upper=np.arange(ct.shape[2])[None,None,:]>35
  spatial.append(dict(phase_id=pid,phase_percent=r["phase_percent"],ts_rv_above_baseline_cut_ml=float((trv&upper).sum()*v),
    ts_rv_outside_authored_ml=float((trv&~rv).sum()*v),authored_rv_outside_ts_ml=float((rv&~trv).sum()*v),
    authored_rv_in_ts_ra_ml=float((rv&auto_arrays["RA"]).sum()*v),
    definition="Label disagreement, not anatomic error; fixed k>35 is a diagnostic partition, not a valve plane"))
  registration.append(dict(phase_id=pid,**t["registration"]))
  phases.append(p)
 out.mkdir(parents=True)
 manifest={"baseline_phase":"phase_00","phases":phases,"limitations":["Unaccepted phase0 contours; uncertain valves, vessels and appendages", "Other phases generated by CT-only registration and target HU; not independently manually traced", "Post-comparison anatomic changes would be unblinded"]}
 write(out/"manifest.local.json",manifest);summary=compare(out/"manifest.local.json",out/"comparison")
 write(out/"diagnostics.json",dict(thresholds=thresholds,supplemental=supp,registration=registration,spatial_disagreement=spatial))
 figures(out,summary,thresholds,supp,registration,spatial)
 return summary

def figures(out,s,thresholds,supp,registration,spatial):
 plt.rcParams.update({"font.family":"DejaVu Sans","font.size":11,"axes.spines.top":False,"axes.spines.right":False})
 def save(fig,name):fig.tight_layout();fig.savefig(out/(name+".png"),dpi=150);plt.close(fig)
 rows=s["rows"];diff=s["phase_differences"]
 for mode in ["absolute","delta"]:
  fig,axs=plt.subplots(2,2,figsize=(13,8),sharex=True)
  for ax,ch in zip(axs.flat,CHAMBERS):
   rr=[r for r in (rows if mode=="absolute" else diff) if r["region"]==ch];x=[r["phase_percent"] for r in rr]
   a="authored_ml" if mode=="absolute" else "delta_authored_ml";b="automatic_ml" if mode=="absolute" else "delta_automatic_ml"
   ax.plot(x,[r[a] for r in rr],"o-",color="#007c91",label="Контуры + перенос + HU 190")
   ax.plot(x,[r[b] for r in rr],"s--",color="#bc5b15",label="TotalSegmentator v2")
   if mode=="absolute":
    bands=[[r["volume_ml"] for r in thresholds if r["region"]==ch and r["phase_percent"]==xx] for xx in x]
    ax.fill_between(x,[min(b) for b in bands],[max(b) for b in bands],color="#007c91",alpha=.18,label="Сценарии HU 170–210")
   else:ax.axhline(0,color="gray",lw=.7)
   ax.set(title=NAMES[ch],ylabel="Объём, мл" if mode=="absolute" else "Изменение от фазы 0%, мл",xlabel="Фаза реконструкции, %");ax.grid(alpha=.2)
  axs.flat[0].legend(fontsize=8);save(fig,mode)
 fig,ax=plt.subplots(figsize=(14,4.5));ids=sorted({r["phase_percent"] for r in diff})
 mat=np.array([[next(r["disagreement_delta_ml"] for r in diff if r["region"]==ch and r["phase_percent"]==x) for x in ids] for ch in CHAMBERS]);lim=max(abs(mat).max(),1)
 im=ax.imshow(mat,cmap="RdBu_r",vmin=-lim,vmax=lim,aspect="auto")
 ax.set_yticks(range(4),[NAMES[c] for c in CHAMBERS]);ax.set_xticks(range(len(ids)),ids);ax.set_xlabel("Фаза реконструкции, %")
 for i in range(4):
  for j in range(len(ids)):ax.text(j,i,f"{mat[i,j]:.1f}",ha="center",va="center",fontsize=8,color="white" if abs(mat[i,j])>lim*.6 else "black")
 fig.colorbar(im,ax=ax,label="ΔV TotalSegmentator − ΔV кандидата, мл");save(fig,"delta_disagreement")
 fig,axs=plt.subplots(2,2,figsize=(13,8),sharex=True)
 for ax,ch in zip(axs.flat,CHAMBERS):
  rr=[r for r in rows if r["region"]==ch];bb=[r for r in supp if r["region"]==ch and r["method"]=="transport"]
  ax.plot([r["phase_percent"] for r in bb],[r["volume_ml"] for r in bb],"o--",label="Перенос бинарной маски")
  ax.plot([r["phase_percent"] for r in rr],[r["authored_ml"] for r in rr],"s-",label="Перенос области + HU 190")
  ax.set(title=NAMES[ch],ylabel="Объём, мл",xlabel="Фаза реконструкции, %");ax.grid(alpha=.2)
 axs.flat[0].legend(fontsize=9);save(fig,"method_dependence")
 fig,axs=plt.subplots(1,2,figsize=(13,4.7))
 for ax,key,title in zip(axs,["outer_heart_candidate","myocardium_intensity_candidate"],["Область внутри наружного контура","Кандидат ткани стенки / миокард TS"]):
  for method,label in [("transport","Кандидат: перенос исходной маски"),("TotalSegmentator","TotalSegmentator (другое определение)")]:
   rr=[r for r in supp if r["region"]==key and r["method"]==method];ax.plot([r["phase_percent"] for r in rr],[r["volume_ml"] for r in rr],"o-",label=label)
  ax.set(title=title,ylabel="Объём, мл",xlabel="Фаза реконструкции, %");ax.grid(alpha=.2)
 axs[0].legend(fontsize=8);save(fig,"outer_and_wall")
 fig,axs=plt.subplots(1,2,figsize=(12,4.5));reg=[r for r in registration if "jacobian_min" in r];x=[int(r["phase_id"][-2:])*5 for r in reg]
 axs[0].plot(x,[r["mae_before_hu"] for r in reg],"o--",label="До совмещения");axs[0].plot(x,[r["mae_after_hu"] for r in reg],"o-",label="После совмещения");axs[0].set_ylabel("Средняя абсолютная разность, HU");axs[0].legend()
 axs[1].plot(x,[r["jacobian_min"] for r in reg],"o-");axs[1].set_ylabel("Минимум определителя Якоби");axs[1].axhline(0,color="red",lw=.8)
 for ax in axs:ax.set_xlabel("Фаза реконструкции, %");ax.grid(alpha=.2)
 save(fig,"registration_qc")
 fig,ax=plt.subplots(figsize=(11,4.5))
 for key,label in [("ts_rv_outside_authored_ml","ПЖ TS вне кандидатного ПЖ"),("authored_rv_outside_ts_ml","Кандидатный ПЖ вне ПЖ TS"),("authored_rv_in_ts_ra_ml","Кандидатный ПЖ внутри ПП TS")]:
  ax.plot([r["phase_percent"] for r in spatial],[r[key] for r in spatial],"o-",label=label)
 ax.set(xlabel="Фаза реконструкции, %",ylabel="Объём несовпадающих областей, мл");ax.legend(fontsize=9);ax.grid(alpha=.2);save(fig,"rv_disagreement")

if __name__=="__main__":
 p=argparse.ArgumentParser(description=__doc__);p.add_argument("--root",type=Path,required=True);p.add_argument("--output",type=Path,required=True);p.add_argument("--expected-phases",type=int,default=20)
 a=p.parse_args();s=assemble(a.root,a.output,a.expected_phases);print(s["phase_count"],s["status"])
