"""Offline reader for every saved pose, common-h fits and CT descriptors."""
from pathlib import Path
import sys, base64, json, argparse
import numpy as np
import pandas as pd
from scipy.io import loadmat
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
from matplotlib.colors import LinearSegmentedColormap
from plotly.offline import get_plotlyjs

ROOT=Path(__file__).resolve().parents[1]
DEFAULT=ROOT/'output/exploratory/scan_localization_20260910'
ERROR_COLOURS=[[0,'#087443'],[.2,'#62bd60'],[.4,'#e0dc60'],[.67,'#ed8950'],[1,'#b52136']]

def encoded(x,dtype='<f4'):return base64.b64encode(np.asarray(x,dtype=dtype).tobytes()).decode()
def records(df):return json.loads(df.to_json(orient='records',force_ascii=False))

def build(out):
    d=np.load(out/'scan_arrays.npz');f=np.load(out/'layered_fits.npz');m=np.load(out/'analysis_maps.npz');ct=np.load(out/'ct_comparison.npz')
    source=json.loads((out/'input_contract.json').read_text(encoding='utf-8'))
    surface=loadmat(Path(source['source_run'])/'live/surface.mat')
    faces=surface['boundary_faces'].astype(np.int64)-1;used,inv=np.unique(faces,return_inverse=True);nodes=surface['nodes_mm'][used];faces=inv.reshape(-1,3)
    flat=d['flat'];ci=flat//len(d['phi']);candidates=pd.read_csv(out/'candidate_requests.csv')
    electrodes=pd.read_csv(out/'candidate_electrodes_ct.csv');profiles=pd.read_csv(out/'candidate_axis_geometry_ct.csv')
    values={k:m[k].ravel()[flat] for k in ['experiment','two_layer','h_eff','loo','joint','robust_experiment','robust_joint','robust_two_layer']}
    ng=np.load(out/'neighbourhood_geometry.npz')
    values.update(robust_distinct=ng['robust_experiment_distinct'].ravel()[flat],valid_fraction=100*m['neighbourhood_valid_fraction'].ravel()[flat])
    values.update(ct_depth=ct['normal_depth_by_centre_mm'][ci],ct_rmse=ct['rmse_with_ct_normal_depth_ohm'],h_delta=ct['h_eff_minus_ct_depth_mm'])
    payload=dict(u=d['u'].tolist(),v=d['v'].tolist(),phi=d['phi'].tolist(),sizes=d['sizes'].tolist(),experiment=d['experiment'].tolist(),rho=d['rho'].tolist(),
        flat=encoded(flat,'<i4'),status=encoded(d['status'],'u1'),xyz=encoded(d['centres'][:,3:6]),
        metrics={k:encoded(v) for k,v in values.items()},fem=encoded(d['Z_fem']),planar=encoded(f['prediction']),
        loo_min=encoded(f['loo_h_min_mm']),loo_max=encoded(f['loo_h_max_mm']),loo_predictions=encoded(f['loo_predictions']),
        known=encoded(m['neighbourhood_known'].ravel()[flat],'u1'),fraction=encoded(m['neighbourhood_valid_fraction'].ravel()[flat]),
        nodes=encoded(nodes),faces=encoded(faces,'<u4'),unique=encoded(ng['unique_centres'],'<i4'),neighbours=records(pd.read_csv(out/'candidate_neighbourhood_diagnostics.csv')),candidates=records(candidates),electrodes=records(electrodes),profiles=records(profiles),colours=ERROR_COLOURS)
    html=TEMPLATE.replace('__PLOTLY__',get_plotlyjs()).replace('__DATA__',json.dumps(payload,ensure_ascii=False,separators=(',',':'),allow_nan=False))
    (out/'localization_and_layers.html').write_text(html,encoding='utf-8')
    fig,axes=plt.subplots(2,2,figsize=(11,10),constrained_layout=True)
    cmap=LinearSegmentedColormap.from_list('errors',[x[1] for x in ERROR_COLOURS]);cmap.set_bad('#e3e6e9')
    names=[('experiment','FEM ↔ эксперимент'),('robust_experiment','Устойчивость: худшая ошибка к эксперименту'),('two_layer','Двуслойная модель ↔ FEM'),('joint','Совместно: max двух ошибок в одной позе')]
    for ax,(key,title) in zip(axes.ravel(),names):
        vals=m[key];best=np.min(np.where(np.isfinite(vals),vals,np.inf),axis=1);best[~np.isfinite(best)]=np.nan
        im=ax.imshow(best.reshape(len(d['v']),len(d['u'])),origin='lower',extent=[-80.5,80.5,-120.5,120.5],vmin=0,vmax=15,cmap=cmap,interpolation='nearest',aspect='equal')
        ax.set(title=title,xlabel='u, мм',ylabel='v, мм',xlim=(-80.5,80.5),ylim=(-120.5,120.5));ax.grid(alpha=.12)
    fig.colorbar(im,ax=axes.ravel().tolist(),label='Минимум по рассчитанным углам, RMSE, Ом; цвет насыщается при 15 Ом',shrink=.7)
    fig.suptitle('Сохранённая часть полного перебора · 475 090 FEM-поз\nСерый: нет значения метрики; причины доступны в интерактивной карте',fontsize=13)
    fig.savefig(out/'localization_overview.png',dpi=150);plt.close(fig)
    print('Reader written:',out/'localization_and_layers.html',flush=True)

TEMPLATE=r'''<!doctype html><html lang="ru"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Боковые сборки: локализация и общее h</title><script>__PLOTLY__</script>
<style>body{margin:0;background:#f3f5f7;color:#1c2936;font:15px/1.5 system-ui,sans-serif}main{max-width:1550px;margin:auto;padding:24px}h1{font-size:28px;margin:0 0 6px}h2{font-size:20px;margin:8px 0}.muted{color:#576573}.card{background:white;border:1px solid #d8dfe4;border-radius:10px;padding:16px;margin:14px 0}.row{display:grid;grid-template-columns:1fr 1.35fr;gap:16px}.plots{height:620px;min-width:0}.smallplot{height:420px;min-width:0}.controls{display:flex;flex-wrap:wrap;gap:14px;align-items:center}select,button{font:inherit;padding:7px;border:1px solid #aebbc5;border-radius:5px;background:white}label{font-weight:600}#selection{background:#eff6f2;padding:12px;border-left:4px solid #21834e}table{border-collapse:collapse;font-size:13px;width:100%}th,td{padding:7px;border-bottom:1px solid #e0e5e9;text-align:right}th:first-child,td:first-child{text-align:left}a{color:#155e99}#busy{color:#a54112;font-weight:600}#error{color:#b42020;white-space:pre-wrap}.chips{display:flex;gap:14px;flex-wrap:wrap}.chip{background:#eaf0f3;padding:5px 9px;border-radius:4px}.note{max-width:1250px}@media(max-width:900px){.row{grid-template-columns:1fr}.plots{height:550px}main{padding:12px}}</style></head>
<body><main><h1>Где сборки согласуются с экспериментом и двуслойной моделью</h1>
<p class="muted">Эксперимент 2 · индивидуальная КТ на вдохе · локальный исследовательский результат, 10 сентября 2026</p>
<div class="chips"><span class="chip">475 090 FEM-поз</span><span class="chip">9 размеров в каждой позе</span><span class="chip">Одно общее h</span><span class="chip">Полный FEM-перебор остановлен</span></div>
<div class="card note"><b>Что означает карта.</b> Зелёные точки имеют меньшую выбранную ошибку. Координаты — кандидаты, совместимые с моделью и данными; фактическое положение наклеенных электродов независимо не восстановлено. Рассчитаны 19 200 из 38 801 центров, по 41 углу. Области без расчёта не считаются плохими.
<br>ρ₁ = 5,552166 и ρ₂ = 30,706947 Ом·м перенесены из прежнего подбора и фиксированы. FEM содержит мягкие ткани, лёгкое, сердце, кости и конечные CEM-контакты. Аналитическая модель содержит два плоских слоя и точечные контакты. Поэтому остаточная ошибка не определяется одной только кривизной.
<br><b>Критическая проверка координат:</b> 16 955 центрам с допустимыми позами соответствуют 10 908 различных точек поверхности. В 92 центрах все 25 соседних проекций совпадают. Минимум ошибки устойчивости 10,315 Ом включает такой случай; при требовании 25 различных центров минимум составляет 12,679 Ом. Это не позволяет объявить найденные зелёные точки надёжными областями установки.<br><b>Устойчивость:</b> худшая RMSE в окне ±2 шага по u, v и φ (125 поз). Требуются все 125 рассчитанных допустимых поз. Это сценарий чувствительности, а не измеренная погрешность наклейки. Пороги 3–10 Ом — исследовательские варианты, не доверительные области.</div>
<div class="card"><div class="controls"><label>Показатель <select id="metric"></select></label><label>Угол <select id="angle"><option value="best">Лучший в каждом центре</option></select></label><label>Предел шкалы ошибок <select id="cap"><option>5</option><option>10</option><option selected>15</option><option>30</option></select> Ом</label><button id="reset">Ракурс сбоку</button><span id="busy">Загрузка…</span></div>
<p id="metric-note" class="muted"></p><div class="row"><div id="map" class="plots"></div><div id="body" class="plots"></div></div><p id="count"></p>
<p class="muted">Серый — нет расчёта; фиолетовый — исключённая поверхность; тёмно-серый — отказ геометрии; голубой — неполное окно соседей; коричневый — в полностью известном окне есть недопустимые позы; бежевый — проекции соседей повторяются или вырождены. Клик по ячейке или 3D-точке открывает её кривые. u ограничено [−80; 80], все 41 угловой слой сохранены.</p></div>
<div class="card"><div class="controls"><label>Показательные кандидаты <select id="candidate"></select></label><label>Показать электроды размера <select id="size"></select> мм</label></div><p id="selection"></p><div class="row"><div id="curves" class="smallplot"></div><div id="profile" class="smallplot"></div></div><p class="muted">Глубина по нормали — путь от поверхности до первого входа в лёгкое; он может содержать кость. Эффективное h определяется электрической подгонкой и не равно этой глубине по определению. Профиль показывает изменение глубины вдоль оси сборки; пропуски означают отсутствие надёжного пересечения. Координаты центра электродной площадки и её фактического центра площади сохранены раздельно.</p></div>
<div class="card"><h2>Кандидаты и численные таблицы</h2><div style="overflow:auto" id="table"></div><p><a href="candidate_electrodes.csv">Координаты 4 электродов × 9 размеров для кандидатов</a> · <a href="candidate_requests.csv">Центры, углы и ошибки кандидатов</a> · <a href="pose_analysis.csv">Все 475 090 поз</a> · <a href="regions.csv">Связные области</a> · <a href="experimental_thresholds.csv">Число поз по порогам</a> · <a href="joint_thresholds.csv">Совместные пороги</a> · <a href="candidate_ct_summary.csv">Геометрия кандидатов</a> · <a href="candidate_neighbourhood_diagnostics.csv">Проверка соседей и повторных координат</a></p>
<p class="muted">Подбор выполнен на всём h ≥ 0 с проверкой предела h → ∞. Гарантированная погрешность глобального минимума RMSE от численной аппроксимации ≤0,001 Ом; итоговые кривые пересчитаны исходным рядом. «Без одного размера» — девять подгонок по восьми оставшимся размерам и прогноз исключённого. Это внутренняя модельная проверка, а не независимая экспериментальная валидация. Данные и Plotly встроены в HTML, сетевые запросы не требуются.</p></div><div id="error"></div></main>
<script id="data" type="application/json">__DATA__</script><script>
'use strict';const D=JSON.parse(document.getElementById('data').textContent);
function dec(s,T=Float32Array){const b=Uint8Array.from(atob(s),c=>c.charCodeAt(0));return new T(b.buffer)}
const S=dec(D.status,Uint8Array),F=dec(D.flat,Int32Array),XYZ=dec(D.xyz),N=dec(D.nodes),B=dec(D.faces,Uint32Array),Y=dec(D.fem),P=dec(D.planar),LP=dec(D.loo_predictions),LO=dec(D.loo_min),HI=dec(D.loo_max),K=dec(D.known,Uint8Array),FR=dec(D.fraction);
const UNIQUE=dec(D.unique,Int32Array);const M=Object.fromEntries(Object.entries(D.metrics).map(([k,v])=>[k,dec(v)])),A=D.phi.length,U=D.u.length,V=D.v.length,C=U*V;
const lookup=new Int32Array(S.length).fill(-1);F.forEach((v,i)=>lookup[v]=i);let currentLayer,selected=0,ready=false;
const q=id=>document.getElementById(id),num=(v,n=2)=>Number.isFinite(v)?v.toFixed(n):v===Infinity?'∞':'—';
const definitions={robust_distinct:['Устойчивость: 25 разных центров','robust_distinct','RMSE, Ом','Худшая ошибка к эксперименту по 125 допустимым соседям. Дополнительно все 25 проекций центров различаются и образуют двумерную область. Шаг параметров всё ещё не равен физическому смещению.'],valid_fraction:['Доля допустимых соседей','experiment','Доля, %','Из 125 номинальных соседних поз. При лучшем угле показывается доля для лучшего согласия с экспериментом, а не максимум доли.'],experiment:['FEM ↔ эксперимент','experiment','RMSE, Ом','Минимум ошибки относительно девяти экспериментальных значений.'],robust_experiment:['Устойчивость согласия с экспериментом','robust_experiment','RMSE, Ом','Худшая ошибка к эксперименту во всех 125 соседних позах.'],two_layer:['Двуслойная модель ↔ FEM','two_layer','RMSE, Ом','Одно h по всем девяти размерам. ρ и номинальная геометрия аналитической сборки фиксированы.'],loo:['Прогноз исключённого размера','loo','RMSE, Ом','RMSE девяти прогнозов: каждый получен без использования своего размера при подборе h.'],joint:['Оба условия одновременно','joint','max RMSE, Ом','max(ошибка FEM к эксперименту, ошибка двуслойной модели к FEM) в одной и той же позе.'],robust_joint:['Устойчивое выполнение обоих условий','robust_joint','max RMSE, Ом','Худшее совместное расхождение по всем 125 соседям.'],robust_two_layer:['Устойчивость двуслойного приближения','robust_two_layer','RMSE, Ом','Худшая ошибка двуслойной модели к FEM по 125 соседям.'],h_eff:['Эффективное h','two_layer','h, мм','При выборе лучшего угла используется минимум ошибки двуслойной модели к FEM. Цвет h не означает качество.'],ct_depth:['Глубина лёгкого по нормали КТ','experiment','Глубина, мм','Первый вход в лёгкое по внутренней нормали к поверхности. При лучшем угле выбирается минимум ошибки к эксперименту.'],ct_rmse:['Двуслойная модель с h по КТ','ct_rmse','RMSE, Ом','Вместо подбора h подставлена глубина первого входа в лёгкое по нормали центра.'],h_delta:['h эффективное минус глубина КТ','two_layer','Разность, мм','При лучшем угле используется минимум ошибки двуслойной модели к FEM. Разность не является ошибкой измерения толщины.']};
for(const [k,v] of Object.entries(definitions))q('metric').add(new Option(v[0],k));q('metric').value='experiment';D.phi.forEach((p,i)=>q('angle').add(new Option('φ = '+p+'°',i)));
D.candidates.forEach(c=>q('candidate').add(new Option(c.candidate_id+' · u='+c.u_mm+', v='+c.v_mm+', φ='+c.phi_deg,c.candidate_id)));q('candidate').add(new Option('Выбрано на карте','custom'));D.sizes.forEach(s=>q('size').add(new Option(s,s)));q('size').value='140';
function scale(){const k=q('metric').value;if(k==='valid_fraction')return {min:0,max:100,colours:D.colours.map(x=>[1-x[0],x[1]]).reverse()};if(k==='h_delta')return {min:-50,max:50,colours:'RdBu'};if(k==='h_eff'||k==='ct_depth')return {min:0,max:80,colours:'Viridis'};return {min:0,max:+q('cap').value,colours:D.colours}}
const statuses=['Не рассчитано','Рассчитано','Отказ геометрии','Вне разрешённой поверхности','Окно соседей неполное','Есть недопустимые соседи','Нет пересечения КТ','Повторные / вырожденные проекции соседей'];
function layer(){const key=q('metric').value,criterion=definitions[key][1],angle=q('angle').value,groups=Array.from({length:8},()=>({x:[],y:[],z:[],color:[],text:[],customdata:[]})),chosen=new Int32Array(C).fill(-1),z=Array.from({length:V},()=>Array(U).fill(null)),bg=z.map(r=>r.slice()),hover=z.map(r=>r.slice());
 for(let c=0;c<C;c++){let row=-1,a=angle==='best'?-1:+angle,state=0;
  if(angle==='best'){let val=Infinity;for(let j=0;j<A;j++){const r=lookup[c*A+j];if(r>=0&&M[criterion][r]<val){val=M[criterion][r];row=r;a=j}}if(row<0){for(let j=0;j<A;j++){const r=lookup[c*A+j];if(r>=0){row=r;a=j;break}}}}
  else row=lookup[c*A+a];
  if(row>=0){state=1;if(!Number.isFinite(M[key][row]))state=key==='robust_distinct'&&UNIQUE[c]!==25?7:key.startsWith('robust')?(K[row]?5:4):6;chosen[c]=row;}
  else if(a>=0)state=S[c*A+a];else {let missing=false,outside=true;for(let j=0;j<A;j++){if(S[c*A+j]===0)missing=true;if(S[c*A+j]!==3)outside=false;}state=missing?0:outside?3:2;}
  let text='Центр '+(c+1)+' · u='+D.u[c%U]+'; v='+D.v[Math.floor(c/U)]+' мм<br>'+statuses[state];if(row>=0)text+='<br>φ='+D.phi[a]+'° · '+definitions[key][2]+': '+num(M[key][row],3)+'<br>FEM↔эксп.: '+num(M.experiment[row],3)+' Ом; 2L↔FEM: '+num(M.two_layer[row],3)+' Ом<br>h='+num(M.h_eff[row],3)+' мм';text+='<br>XYZ: '+[0,1,2].map(k=>num(XYZ[c*3+k],3)).join(', ')+' мм';
  const g=groups[state];g.x.push(XYZ[3*c]);g.y.push(XYZ[3*c+1]);g.z.push(XYZ[3*c+2]);g.text.push(text);g.customdata.push(c);g.color.push(row>=0?M[key][row]:null);const v=Math.floor(c/U),u=c%U;hover[v][u]=text;if(state===1)z[v][u]=M[key][row];else bg[v][u]=state;
 }return {groups,z,bg,hover,chosen};}
const axis=(a,k)=>Array.from({length:a.length/3},(_,i)=>a[3*i+k]);const mesh={type:'mesh3d',x:axis(N,0),y:axis(N,1),z:axis(N,2),i:axis(B,0),j:axis(B,1),k:axis(B,2),color:'#c5ccd2',opacity:.24,hoverinfo:'skip',showlegend:false};
const sc=['#e1e4e7',null,'#747e87','#a48bbb','#94c7e2','#b99e85','#dcbed0','#e2cd90'];
function trace(g,s){const a=scale();return {type:'scatter3d',mode:'markers',x:g.x,y:g.y,z:g.z,text:g.text,customdata:g.customdata,hovertemplate:'%{text}<extra></extra>',name:statuses[s],showlegend:false,marker:{size:s===1?2.5:1.8,color:s===1?g.color:sc[s],colorscale:a.colours,cmin:a.min,cmax:a.max,showscale:s===1,colorbar:{title:{text:definitions[q('metric').value][2]},len:.6,thickness:12}}};}
function scene(){return {xaxis:{title:{text:'x, мм'}},yaxis:{title:{text:'y, мм'}},zaxis:{title:{text:'z, мм'}},aspectmode:'data',camera:{eye:{x:-1.9,y:.5,z:.3},up:{x:0,y:0,z:1}}}}
const config={responsive:true,displaylogo:false,scrollZoom:true};const mark={type:'scatter3d',mode:'markers+text',x:[],y:[],z:[],text:[],name:'Электроды',marker:{color:'#111',size:5},textposition:'top center',hovertemplate:'%{text}<extra></extra>'};
function mapData(l){const s=scale();return [{type:'heatmap',x:D.u,y:D.v,z:l.bg,zmin:0,zmax:7,colorscale:sc.flatMap((colour,i)=>[[Math.max(0,(i-.5)/7),colour||'white'],[Math.min(1,(i+.5)/7),colour||'white']]),showscale:false,text:l.hover,hovertemplate:'%{text}<extra></extra>',zsmooth:false,connectgaps:false},{type:'heatmap',x:D.u,y:D.v,z:l.z,zmin:s.min,zmax:s.max,colorscale:s.colours,colorbar:{title:{text:definitions[q('metric').value][2]},thickness:12},text:l.hover,hovertemplate:'%{text}<extra></extra>',hoverongaps:false,zsmooth:false,connectgaps:false}]}
function note(l){q('metric-note').textContent=definitions[q('metric').value][3]+(q('angle').value==='best'?' Лучший угол выбирается только среди готовых поз.':'');q('count').textContent=l.groups.map((g,i)=>statuses[i]+': '+g.x.length).join(' · ')}
async function redraw(){q('busy').textContent='Обновление…';const l=layer();currentLayer=l;const traces=[mesh,...l.groups.map(trace),mark];await Promise.all([Plotly.react('body',traces,{margin:{l:0,r:0,t:0,b:0},scene:scene(),uirevision:'body'},config),Plotly.react('map',mapData(l),{margin:{l:60,r:100,t:25,b:55},xaxis:{title:{text:'u, мм'},range:[-80.5,80.5],constrain:'domain'},yaxis:{title:{text:'v, мм'},range:[-120.5,120.5],scaleanchor:'x',scaleratio:1,constrain:'domain'},uirevision:'map'},config)]);note(l);q('busy').textContent='';}
async function showRow(row,candidate=null){if(row<0)return;selected=row;const flat=F[row],c=Math.floor(flat/A),ai=flat%A;let text='Центр '+(c+1)+': u='+D.u[c%U]+', v='+D.v[Math.floor(c/U)]+' мм; φ='+D.phi[ai]+'°. XYZ = ('+[0,1,2].map(k=>num(XYZ[c*3+k],3)).join('; ')+') мм.';
 text+=' FEM↔эксперимент: '+num(M.experiment[row],3)+' Ом; 2L↔FEM: '+num(M.two_layer[row],3)+' Ом; h = '+num(M.h_eff[row],3)+' мм. При исключении размера h = '+num(LO[row],2)+'…'+num(HI[row],2)+' мм; ошибка прогноза '+num(M.loo[row],3)+' Ом.';const dg=D.neighbours.find(v=>D.candidates.find(c=>c.flat_index===flat)?.candidate_id===v.candidate_id);if(dg)text+=' Соседи: '+dg.valid+'/'+dg.neighbours_in_grid+' допустимы; разных центров '+dg.unique_projected_centres+' из 25; ошибка среди допустимых до '+num(dg.rmse_max_valid_ohm,2)+' Ом.';q('selection').textContent=text;
 const vals=a=>Array.from(a.slice(row*9,row*9+9));await Plotly.react('curves',[{x:D.sizes,y:D.experiment,name:'Эксперимент',mode:'lines+markers',line:{color:'#232b33',dash:'dot'}},{x:D.sizes,y:vals(Y),name:'FEM',mode:'lines+markers',line:{color:'#136fba'}},{x:D.sizes,y:vals(P),name:'2 слоя, общее h',mode:'lines+markers',line:{color:'#209449'}},{x:D.sizes,y:vals(LP),name:'Прогноз без размера',mode:'markers',marker:{symbol:'x',color:'#c5741c',size:8}}],{title:{text:'Девять размеров в выбранной позе'},margin:{l:60,r:10,t:45,b:80},xaxis:{title:{text:'Размер L, мм'}},yaxis:{title:{text:'Импеданс, Ом'}},legend:{orientation:'h',y:-.24}},config);
 const cand=candidate||D.candidates.find(v=>v.flat_index===flat);q('candidate').value=cand?cand.candidate_id:'custom';
 const ep=cand?D.electrodes.filter(v=>v.candidate_id===cand.candidate_id&&v.L_mm===+q('size').value):[];
 Object.assign(mark,{x:ep.length?ep.map(v=>v.x_mm):[XYZ[c*3]],y:ep.length?ep.map(v=>v.y_mm):[XYZ[c*3+1]],z:ep.length?ep.map(v=>v.z_mm):[XYZ[c*3+2]],text:ep.length?ep.map(v=>v.electrode):['Выбранный центр']});await Plotly.restyle('body',{x:[mark.x],y:[mark.y],z:[mark.z],text:[mark.text]},[9]);
 const profile=cand?D.profiles.filter(v=>v.candidate_id===cand.candidate_id):[];
 await Plotly.react('profile',[{x:profile.map(v=>v.axis_s_mm),y:profile.map(v=>v.lung_entry_mm),name:'Глубина: локальная нормаль',mode:'lines',connectgaps:false},{x:profile.map(v=>v.axis_s_mm),y:profile.map(v=>v.parallel_lung_entry_mm),name:'Глубина: параллельные лучи',mode:'lines',connectgaps:false,line:{dash:'dot'}},{x:[-70,70],y:[M.h_eff[row],M.h_eff[row]],name:'h эффективное',mode:'lines',line:{color:'#209449',dash:'dash'}},{x:profile.map(v=>v.axis_s_mm),y:profile.map(v=>v.bone_before_lung_mm),name:'Кость до лёгкого',mode:'lines',connectgaps:false,line:{color:'#9c7652'}}],{title:{text:profile.length?'Геометрия вдоль оси кандидата':'Подробный профиль рассчитан для кандидатов из списка'},margin:{l:60,r:10,t:45,b:80},xaxis:{title:{text:'Смещение вдоль оси, мм'},range:[-70,70]},yaxis:{title:{text:'Глубина / длина пути, мм'}},legend:{orientation:'h',y:-.24}},config);
}
function error(e){q('error').textContent=String(e.stack||e);q('busy').textContent='Ошибка отображения'}
async function start(){await redraw();q('map').on('plotly_click',e=>{const p=e.points[0],c=D.v.indexOf(p.y)*U+D.u.indexOf(p.x);showRow(currentLayer.chosen[c]).catch(error)});q('body').on('plotly_click',e=>{const c=e.points[0].customdata;if(Number.isInteger(c))showRow(currentLayer.chosen[c]).catch(error)});await showRow(lookup[D.candidates[0].flat_index],D.candidates[0]);ready=true;q('busy').textContent='';window.analysisReady=true}
for(const id of ['metric','angle','cap'])q(id).addEventListener('change',()=>redraw().then(()=>showRow(selected)).catch(error));q('candidate').addEventListener('change',()=>{const c=D.candidates.find(v=>v.candidate_id===q('candidate').value);if(c)showRow(lookup[c.flat_index],c).catch(error)});q('size').addEventListener('change',()=>showRow(selected).catch(error));q('reset').addEventListener('click',()=>Plotly.relayout('body',{'scene.camera':scene().camera}));
q('table').innerHTML='<table><tr><th>Кандидат</th><th>u</th><th>v</th><th>φ</th><th>FEM↔эксп., Ом</th><th>2L↔FEM, Ом</th><th>h, мм</th><th>Устойчивость к эксперименту, Ом</th></tr>'+D.candidates.map(c=>'<tr><td>'+c.candidate_id+'</td><td>'+c.u_mm+'</td><td>'+c.v_mm+'</td><td>'+c.phi_deg+'</td><td>'+num(c.rmse_experiment_ohm,3)+'</td><td>'+num(c.rmse_2L_FEM_ohm,3)+'</td><td>'+num(c.h_eff_mm,2)+'</td><td>'+num(c.robust_experiment_ohm,3)+'</td></tr>').join('')+'</table>';start().catch(error);
</script></body></html>'''

if __name__=='__main__':
    p=argparse.ArgumentParser(description=__doc__);p.add_argument('--out',type=Path,default=DEFAULT);args=p.parse_args();build(args.out)
