"""Scientific prose and figure captions for notebook 20.10.

This module is intentionally a post-processing layer.  It is applied after
``revise_2010_cleanup.apply`` and before the geometry and PEM revisions.  The
module edits only reader-facing prose, plot labels, and saved caption
outputs; it does not execute a field calculation and does not alter numerical
tables or arrays.

The selectors use stable semantic fragments of cell source rather than cell
indices or the random notebook cell ids generated by the report builder.
``apply(nb)`` accepts an ``nbformat.NotebookNode`` or a dictionary-shaped
notebook and is idempotent.
"""

from __future__ import annotations

import json
import re
from typing import Callable, Iterable, Mapping, MutableSequence


MODULE_VERSION = "2026-09-14.prose-caption-catalog.v2"
MARKER_PREFIX = "revise_2010_prose"


def _caption_marker(key: str) -> str:
    return f"<!-- {MARKER_PREFIX}:figure:{key} -->"


# The catalog is deliberately kept in this module so the main report builder
# can discover the editorial contract without depending on a second asset.
# Every entry describes a retained figure.  Sections 3.1, 4, and 13 are owned
# by other post-processors and are deliberately absent from this catalog.
CAPTION_CATALOG = [
    {
        "key": "fig-3-1-historical-anatomy",
        "section": "3",
        "selector": "fig3d = go.Figure()",
        "caption": (
            "**Рисунок 3.1. Объёмная сцена исходной локализации и расположение "
            "электродных сборок.** На сцене показаны наружная поверхность тела, "
            "лёгкие, сердце и кости; цветные точки — центроиды 36 дискретных "
            "площадок девяти сборок, а отдельными обозначениями выделены сборка "
            "140 мм, общая ось, центр и вспомогательная плоскость. Координатные "
            "оси $x$, $y$ и $z$ заданы в миллиметрах. "
            "\n\n"
            "Фигуру следует читать как контроль масштаба и взаимного положения "
            "объектов. Она относится к историческому кандидату, использованному "
            "в разделах 1–10; этот кандидат отличается от C01 раздела 20 и не "
            "является изображением текущей окончательной позы. Проекция "
            "центроида на поверхность и полный набор граничных граней контакта "
            "могут различаться. Поэтому фигура не подтверждает фактическую "
            "наклейку электродов и не задаёт точность локализации. Текущий C01 "
            "и его координаты приведены отдельно в разделе 20."
        ),
    },
    {
        "key": "fig-5-1-thickness-profile",
        "section": "5",
        "selector": "h_fit_rmse =",
        "caption": (
            "**Рисунок 5.1. Профили расстояния от кожи до лёгкого вдоль оси "
            "исторического сечения.** По горизонтальной оси отложена продольная "
            "координата $s$, мм; по вертикальной — расстояние $h(s)$, мм. "
            "Показаны профиль выбранного сечения, диагностические расстояния по "
            "локальной нормали кожи и до ближайшей точки лёгкого, а также робастная "
            "полиномиальная аппроксимация четвёртой степени. Вертикальные отметки "
            "показывают положение границ сборок разных размеров. "
            "\n\n"
            "Кривые позволяют увидеть продольную неоднородность и сравнить разные "
            "геометрические определения глубины; RMSE полиномиальной аппроксимации "
            "0,558 мм относится только к сглаживанию этого профиля. Расстояние "
            "может включать кость и не является автоматически толщиной мягких "
            "тканей или электрически эффективной толщиной. Профиль используется "
            "далее как вход эвристических слоистых приближений, а их электрическая "
            "эквивалентность проверяется по импедансу."
        ),
    },
    {
        "key": "fig-7-1-inverse-diagnostics",
        "section": "7",
        "selector": "best_so_far = np.minimum.accumulate",
        "caption": (
            "**Рисунок 7.1. Диагностика исходного кандидата обратной задачи.** "
            "На панели а показаны экспериментальная и FEM-кривые $Z(L)$ в омах "
            "для размеров $L$ в миллиметрах; панель б содержит подписанные остатки "
            "$Z_{\\rm FEM}-Z_{\\rm эксп}$; панель в сопоставляет номинальные и "
            "фактические размахи токовых и измерительных контактов в миллиметрах; "
            "панель г показывает значение критерия $J$ по мере обращений к нему. "
            "\n\n"
            "Кривые и остатки характеризуют согласование выбранного расчётного "
            "кандидата с девятью агрегированными наблюдениями. Панель в отделяет "
            "ошибку дискретизации контактов от ошибки сопротивлений, а панель г "
            "показывает историю обращений к критерию, а не число решённых FEM-задач. "
            "Остатки включают расхождение модели и измерения; доверительные полосы "
            "не строились. Следующий анализ рассматривает, какие из пяти параметров "
            "действительно различимы по таким данным."
        ),
    },
    {
        "key": "fig-8-1-finite-secants",
        "section": "8",
        "selector": "jacobian_column_norm * sensitivity.plausible_scale",
        "caption": (
            "**Рисунок 8.1. Нормы масштабированных конечных секущих.** По оси "
            "абсцисс расположены пять параметров исходной задачи, по оси ординат "
            "в логарифмическом масштабе — нормы столбцов $J^{(\\Delta)}S$, Ом. "
            "Каждый столбец умножен на заранее заданный масштаб параметра, чтобы "
            "сопоставить сопротивления, координаты и угол с разными единицами. "
            "\n\n"
            "Большая высота столбца означает больший отклик девяти импедансов на "
            "выбранное конечное возмущение в принятой нормировке. Она не означает "
            "меньшую ошибку оценки и не является мерой физиологической значимости. "
            "Секущие по координатам позы зависят от переключения дискретных "
            "граничных граней; поэтому рисунок служит диагностикой конкретного шага, "
            "а не графиком непрерывной производной. Далее эта зависимость проверяется "
            "через сингулярный спектр и слабое компенсирующее направление."
        ),
    },
    {
        "key": "fig-11-4-direct-operators",
        "section": "11.4",
        "selector": "display_direct()",
        "caption": (
            "**Рисунок 11.4а. Прямое сравнение пяти операторов для одного синтетического состояния.** "
            "Слева представлены импедансы для девяти размеров $L$, мм; в центре — знаковые разности "
            "аналитических моделей относительно КТ/PEM; справа — соответствующие разности пространственных "
            "моделей. По горизонтальной оси отложен размер сборки $L$, мм, по вертикальной — импеданс "
            "или разность импедансов, Ом. Близость к нулю означает лучшее воспроизведение выбранного "
            "референса в данном состоянии; раздельные масштабы панелей нельзя сравнивать по высоте линий "
            "без чтения их осей. Нулевая линия КТ получена вычитанием результата из самого себя и не "
            "является нулевой физической погрешностью FEM."
            "\n\n"
            "**Результат для этого состояния.** При заранее заданных и не подогнанных сопротивлениях "
            "$\\rho_1=4$ и $\\rho_2=16$ Ом·м RMSE относительно КТ/PEM составляет 11,248 Ом для М1, "
            "12,767 Ом для М2, 0,0540 Ом для М3 и 0,0405 Ом для М4. Переменная пространственная форма "
            "даёт наименьший суммарный RMSE среди четырёх кандидатов по девяти размерам, но не минимальную "
            "ошибку для каждого размера. Добавление профиля глубины в М2 ухудшило прямой прогноз относительно "
            "М1: дополнительная геометрическая информация внутри эвристического усреднения не гарантирует "
            "более точного электрического поля."
            "\n\n"
            "Этот опыт оценивает только прямой оператор при известных сопротивлениях и не устанавливает "
            "точность обратного восстановления неизвестных $\\rho_1,\\rho_2$. Для этого нужны синтетические "
            "наблюдения с известными параметрами и отдельная инверсия. В таблице и на рисунке следует "
            "различать невязки относительно PEM и CEM: различие контактного представления является "
            "самостоятельной составляющей сравнения. Новые варианты включения в полупространстве здесь "
            "ещё не рассчитаны."
        ),
    },
    {
        "key": "fig-11-5-1-historical-fixed-depth",
        "section": "11.5",
        "selector": "direct_error_table = pd.DataFrame",
        "caption": (
            "**Рисунок 11.5.1. Историческое сравнение размерных кривых при "
            "фиксированной геометрической глубине.** По оси $L$ отложен номинальный "
            "размер сборки, мм, по оси $Z$ — передаточный импеданс, Ом. Показаны "
            "экспериментальный ряд, обычная плоская двухслойная формула, её "
            "адаптированный вариант с переменным профилем и CT/FEM-кривая. "
            "\n\n"
            "Все кривые относятся к раннему положению, а не к C01 раздела 20; "
            "сопротивления перенесены из исходного кандидата и не переоценивались "
            "в этой фигуре. Расстояния и аналитические контакты идеализированы, "
            "поэтому близость двух линий не отделяет ошибку геометрии от ошибки "
            "контакта. Численные RMS и ограничения приведены непосредственно после "
            "рисунка; далее проверяется конечная лёгочная область."
        ),
    },
    {
        "key": "fig-11-5-2-finite-lung-profile",
        "section": "11.5.1",
        "selector": "finite_lung_profile.png",
        "caption": (
            "**Рисунок 11.5.2. Пересечения замкнутой лёгочной поверхности в "
            "историческом сечении.** По горизонтальной оси показана координата вдоль "
            "сборки, мм; по вертикальной — глубина относительно профиля кожи, мм. "
            "Отдельные полосы и линии соответствуют последовательным входам и выходам "
            "луча из лёгочной маски. Первый вход выделен как граница, используемая в "
            "эвристическом профиле. "
            "\n\n"
            "Рисунок показывает, что под одной сборкой возможны несколько лёгочных "
            "интервалов. Наличие таких пересечений установлено геометрически и не "
            "позволяет по одному профилю определить их электрический вес или отнести "
            "конкретный выход к куполу диафрагмы. Полный объём сохраняется только в "
            "пространственном расчёте; плоские варианты используют выбранную схему "
            "редукции."
        ),
    },
    {
        "key": "fig-11-5-3-finite-lung-comparison",
        "section": "11.5.1",
        "selector": "comparison.png",
        "caption": (
            "**Рисунок 11.5.3. Сравнение плоских и пространственных вариантов при "
            "конечной лёгочной области.** По горизонтальной оси отложен размер $L$, "
            "мм; по вертикальной — импеданс $Z$, Ом. Рядом с размерным рядом "
            "сопоставлены плоские варианты с одной или несколькими толщинами, "
            "двухтканный FEM с замкнутой лёгочной маской и FEM с контролируемым "
            "продолжением лёгкого после первого входа. "
            "\n\n"
            "Замена замкнутой маски продолженной областью изменяет FEM на 0,466–3,432 "
            "Ом в данном опыте; это эффект конкретной геометрической операции. "
            "Числа не являются оценкой влияния диафрагмы как отдельной ткани. "
            "Сравнение плоских вариантов с FEM содержит также различие точечных и "
            "конечных электродов. Поэтому дальнейший выбор модели должен опираться "
            "на ошибку обратного восстановления, а не только на близость одной кривой."
        ),
    },
    {
        "key": "fig-11-5-4-parameter-fit",
        "section": "11.5.2",
        "selector": "Z_plain_free_fit =",
        "caption": (
            "**Рисунок 11.5.4. Размерные кривые после отдельной параметрической "
            "подгонки.** По оси $L$ показан размер сборки, мм, по оси $Z$ — импеданс, "
            "Ом. Для каждой аналитической схемы параметры подбирались по тем же "
            "девяти экспериментальным значениям; CT/FEM приведён как сохранённая "
            "кривая исходного кандидата. "
            "\n\n"
            "Меньший остаток после подгонки означает, что модель может описать данный "
            "ряд с помощью своих параметров. Он не отделяет физическую адекватность "
            "геометрии от компенсации: например, свободная $h$ может уйти от "
            "геометрического расстояния, а сопротивление — к границе диапазона. "
            "Фигура поэтому является диагностикой идентифицируемости и компенсации, "
            "а не независимой проверкой точности."
        ),
    },
    {
        "key": "fig-12-1-breath-and-contact-discretization",
        "section": "12",
        "selector": "geometry_diagnostic = grids.copy()",
        "caption": (
            "**Рисунок 12.1. Дыхательные уровни, приращения и дискретная геометрия "
            "контактов.** Четыре панели используют общую ось абсцисс — номинальный "
            "размер сборки $L$, мм. На панели а показаны импедансы на задержке вдоха "
            "и выдоха, на панели б — приращения между соседними размерами, на панели "
            "в — фактические и номинальные размахи токовых и измерительных контактов, "
            "на панели г — диапазон площадей дискретных контактных пятен, мм². "
            "Импедансы и их разности выражены в омах. "
            "\n\n"
            "Панель а показывает немонотонный размерный ряд, а панель б позволяет "
            "сравнить его локальные изменения с FEM и обычной двухслойной формулой. "
            "Панели в–г показывают, что номинальный размер не полностью определяет "
            "дискретную геометрию. Последовательные записи дыхательных состояний и "
            "размеров не являются независимыми повторениями; причина максимума при "
            "60 мм по этой фигуре не установлена. Следующая проверка требует "
            "повторных установок и сгущения поверхности."
        ),
    },
    {
        "key": "fig-14-1-contact-reconstruction",
        "section": "14",
        "selector": "old_legacy_curve.L_mm",
        "caption": (
            "**Рисунок 14.1. Воспроизведение исторической контактной функции.** "
            "По оси $L$ показан размер сборки, мм, по оси $Z$ — импеданс, Ом. "
            "Сопоставлены архивная FEM-кривая, результат наиболее раннего доступного "
            "алгоритма и реконструкция быстрого построения площадок при одной и той "
            "же исторической точке. "
            "\n\n"
            "Фигура показывает, насколько изменение правил выбора граничных граней "
            "может изменить прямой оператор. Совпадение семи из девяти импедансов в "
            "реконструкции не восстанавливает два неустановленных контакта и не "
            "подтверждает архивную физическую модель. Результат относится к истории "
            "кода и служит объяснением происхождения чисел."
        ),
    },
    {
        "key": "fig-14-2-cause-decomposition",
        "section": "14",
        "selector": "forward_change_rms",
        "caption": (
            "**Рисунок 14.2. Разложение причин изменения исторического результата.** "
            "Левая панель показывает размерные кривые для прежней и текущей контактной "
            "реализации, разных привязок размера и разных стартовых точек; оси имеют "
            "единицы мм для $L$ и Ом для $Z$. Правая панель показывает значения "
            "критерия $J$ для тех же контрольных прогонов. "
            "\n\n"
            "Сравнение читается попарно: при фиксированных остальных условиях изменение "
            "контактной дискретизации существенно меняет прямую кривую, а замена "
            "дублированной записи 100 мм на независимую 90 мм меняет её аргумент. "
            "Разные старты оптимизатора могут приводить к разным дискретным кандидатам. "
            "Эти прогоны не образуют единого рейтинга точности и не дают независимой "
            "координаты фактической наклейки."
        ),
    },
    {
        "key": "fig-14-3-current-historical-summary",
        "section": "14",
        "selector": "best_exact_residual",
        "caption": (
            "**Рисунок 14.3. Сопоставление текущего и исторического CEM-кандидатов.** "
            "На левой панели приведены экспериментальная и рассчитанные зависимости "
            "$Z(L)$, где $L$ выражен в миллиметрах, а $Z$ — в омах; на правой панели "
            "показаны подписанные остатки относительно эксперимента. Нулевая линия "
            "правой панели соответствует совпадению модели и наблюдения. "
            "\n\n"
            "Исторический CEM-кандидат рассчитан с сопротивлениями отклонённой точки "
            "и потому не является повторной оценкой текущего кандидата. Меньший RMSE "
            "при фиксированных параметрах не отменяет выхода угла на границу старого "
            "поиска. Фигура предназначена для прослеживаемости, а не для выбора "
            "окончательной позы."
        ),
    },
    {
        "key": "fig-16-1-singular-spectrum",
        "section": "16",
        "selector": "weak_delta_z = J @ weak_physical",
        "caption": (
            "**Рисунок 16.1. Спектр масштабированной матрицы конечных секущих.** "
            "По оси абсцисс расположен номер сингулярного числа, по оси ординат в "
            "логарифмическом масштабе — его значение в омах после заданного "
            "масштабирования сопротивлений, координат и угла. Разрыв между большим "
            "и малым значением показывает слабое направление линейной диагностической "
            "модели. "
            "\n\n"
            "Число обусловленности около 79,4 означает, что в выбранной нормировке "
            "наиболее слабое направление заметно хуже обусловлено, чем наиболее "
            "сильное. Это не стандартная ошибка и не доверительный интервал: матрица "
            "построена конечными шагами, а геометрические контакты дискретны. "
            "Следующий контроль должен проверить слабое направление полным нелинейным "
            "расчётом и изменением шагов."
        ),
    },
    {
        "key": "fig-17-1-breathing-diagnostic",
        "section": "17",
        "selector": "volume_scenarios = pd.DataFrame",
        "caption": (
            "**Рисунок 17.1. Дыхательные уровни и линейная диагностическая подгонка.** "
            "На левой панели показаны уровни $Z$ на задержке глубокого вдоха и выдоха "
            "для размеров $L$, мм; на правой — измеренная разность $Z_{\\rm вд}-Z_{\\rm "
            "выд}$ и её линейные приближения через изменение только $\\rho_2$ либо "
            "обоих сопротивлений. Все вертикальные значения выражены в омах, "
            "приращения сопротивления — в Ом·м. "
            "\n\n"
            "Фигура отвечает на вопрос, насколько выбранная фиксированная геометрия "
            "может воспроизвести наблюдаемую дыхательную разность в первом линейном "
            "приближении. Большое приращение $\\rho_2$ показывает недостаточность "
            "такой интерпретации как доказательства физиологического изменения: "
            "линейность, неизменность геометрии и вклад $\rho_1$ не подтверждены. "
            "Сценарные значения Maxwell–Garnett ниже являются отдельной модельной "
            "оценкой, а не независимым измерением."
        ),
    },
]


def _get(cell, key, default=None):
    if hasattr(cell, "get"):
        return cell.get(key, default)
    return getattr(cell, key, default)


def _set(cell, key, value):
    try:
        cell[key] = value
    except (TypeError, AttributeError):
        setattr(cell, key, value)


def _source(cell) -> str:
    value = _get(cell, "source", "")
    return "".join(value) if isinstance(value, list) else str(value)


def _set_source(cell, value: str) -> None:
    _set(cell, "source", value)


def _cells(nb) -> MutableSequence:
    cells = _get(nb, "cells")
    if cells is None:
        raise TypeError("Notebook must expose a cells sequence")
    return cells


def _is_markdown(cell) -> bool:
    return _get(cell, "cell_type") == "markdown"


def _is_code(cell) -> bool:
    return _get(cell, "cell_type") == "code"


def _find_cell(cells: Iterable, predicate: Callable[[object, str], bool]):
    for cell in cells:
        src = _source(cell)
        if predicate(cell, src):
            return cell
    return None


def _new_markdown_cell(source: str, key: str):
    try:
        from nbformat.v4 import new_markdown_cell

        cell = new_markdown_cell(source=source)
    except Exception:  # pragma: no cover - fallback for minimal notebook stubs
        cell = {"cell_type": "markdown", "metadata": {}, "source": source}
    stable_id = "revise-2010-" + re.sub(r"[^a-zA-Z0-9-]+", "-", key).strip("-")
    _set(cell, "id", stable_id[:64])
    metadata = _get(cell, "metadata", {}) or {}
    metadata = dict(metadata)
    metadata[MARKER_PREFIX] = {"module_version": MODULE_VERSION, "key": key}
    _set(cell, "metadata", metadata)
    return cell


def _caption_marker_in_source(source: str) -> bool:
    return source.lstrip().startswith(f"<!-- {MARKER_PREFIX}:figure:")


def _ensure_caption_after(cells: MutableSequence, selector: Callable[[object, str], bool], key: str, caption: str) -> bool:
    """Insert or refresh one caption cell immediately after its figure cell."""
    target = _find_cell(cells, selector)
    if target is None:
        return False

    marker = _caption_marker(key)
    caption_source = marker + "\n\n" + caption.strip() + "\n"
    target_index = cells.index(target)
    existing_index = None
    existing = None
    for index, cell in enumerate(cells):
        if marker in _source(cell):
            existing_index, existing = index, cell
            break

    if existing is not None:
        _set_source(existing, caption_source)
        metadata = dict(_get(existing, "metadata", {}) or {})
        metadata[MARKER_PREFIX] = {"module_version": MODULE_VERSION, "key": key}
        _set(existing, "metadata", metadata)
        # Keep the order of several captions belonging to one output cell.
        # If the caption is already in the contiguous caption block, refreshing
        # its text is sufficient and avoids reversing 11.5.2/11.5.3.
        if existing_index > target_index and all(
                _caption_marker_in_source(_source(cell))
                for cell in cells[target_index + 1:existing_index]):
            return True
        cells.pop(existing_index)
        if existing_index < target_index:
            target_index -= 1
    else:
        existing = _new_markdown_cell(caption_source, key)

    insertion_index = target_index + 1
    while insertion_index < len(cells) and _caption_marker_in_source(_source(cells[insertion_index])):
        insertion_index += 1
    cells.insert(insertion_index, existing)
    return True


def _output_text(output) -> str:
    pieces = []
    data = _get(output, "data", {}) or {}
    for value in data.values() if hasattr(data, "values") else []:
        pieces.append("".join(value) if isinstance(value, list) else str(value))
    value = _get(output, "text", "")
    pieces.append("".join(value) if isinstance(value, list) else str(value))
    return "\n".join(pieces)


def _markdown_output(text: str):
    import nbformat as nbf

    return nbf.v4.new_output(
        "display_data",
        data={
            "text/markdown": text,
            "text/plain": "<IPython.core.display.Markdown object>",
        },
        metadata={},
    )


INTERLEAVED_CAPTION_KEYS = frozenset({
    "fig-11-5-2-finite-lung-profile",
    "fig-11-5-3-finite-lung-comparison",
    "fig-14-1-contact-reconstruction",
    "fig-14-2-cause-decomposition",
    "fig-14-3-current-historical-summary",
})


def _caption_for(key: str) -> str:
    return next(item["caption"] for item in CAPTION_CATALOG if item["key"] == key)


def _remove_generated_caption_cells(cells: MutableSequence, keys: Iterable[str]) -> int:
    """Remove caption cells made by an older version of this module."""
    keyset = set(keys)
    kept = []
    removed = 0
    for cell in cells:
        metadata = _get(cell, "metadata", {}) or {}
        record = metadata.get(MARKER_PREFIX) if hasattr(metadata, "get") else None
        if isinstance(record, dict) and record.get("key") in keyset:
            removed += 1
        else:
            kept.append(cell)
    if removed:
        cells[:] = kept
    return removed


def _inject_caption_after_source_line(
    target,
    anchor: str,
    key: str,
    *,
    display_figure: bool,
) -> bool:
    """Insert an executable figure/caption pair after a semantic source anchor."""
    src = _source(target)
    marker = _caption_marker(key)
    if marker in src or anchor not in src:
        return False

    start = src.index(anchor)
    end = start + len(anchor)
    line_end = src.find("\n", end)
    if line_end < 0:
        line_end = len(src)
    line_start = src.rfind("\n", 0, end) + 1
    indent_match = re.match(r"[ \t]*", src[line_start:end])
    indent = indent_match.group(0) if indent_match else ""
    literal = json.dumps(
        marker + "\n\n" + _caption_for(key).strip(),
        ensure_ascii=False,
    )
    lines = []
    if display_figure:
        lines.extend([
            f"{indent}display(fig)",
            f"{indent}plt.close(fig)",
        ])
    lines.append(f"{indent}display(Markdown({literal}))")
    insertion = "\n" + "\n".join(lines)
    _set_source(target, src[:line_end] + insertion + src[line_end:])
    return True


def _caption_output_matches(output, expected: str) -> bool:
    data = _get(output, "data", {}) or {}
    return hasattr(data, "get") and data.get("text/markdown") == expected


def _is_image_output(output) -> bool:
    data = _get(output, "data", {}) or {}
    return hasattr(data, "__contains__") and "image/png" in data


def _ensure_interleaved_outputs(
    cells: MutableSequence,
    selector: Callable[[object, str], bool],
    keys: Sequence[str],
) -> bool:
    """Keep captions immediately after PNGs in the source-defined figure order."""
    target = _find_cell(cells, selector)
    if target is None:
        return False

    outputs = list(_get(target, "outputs", []) or [])
    image_positions = [i for i, output in enumerate(outputs) if _is_image_output(output)]
    if len(image_positions) != len(keys):
        return False

    markers = [_caption_marker(key) for key in keys]
    layout_ok = all(
        position + 1 < len(outputs)
        and markers[offset] in _output_text(outputs[position + 1])
        for offset, position in enumerate(image_positions)
    )
    marker_counts_ok = all(
        sum(marker in _output_text(output) for output in outputs) == 1
        for marker in markers
    )
    if layout_ok and marker_counts_ok:
        changed = False
        for offset, position in enumerate(image_positions):
            expected = markers[offset] + "\n\n" + _caption_for(keys[offset]).strip()
            if not _caption_output_matches(outputs[position + 1], expected):
                outputs[position + 1] = _markdown_output(expected)
                changed = True
        if changed:
            _set(target, "outputs", outputs)
        return changed

    # An older run may have put these captions after the whole image block.
    # Remove only our own caption outputs, then rebuild the source-defined pairs.
    cleaned = [
        output for output in outputs
        if not any(marker in _output_text(output) for marker in markers)
    ]
    image_positions = [i for i, output in enumerate(cleaned) if _is_image_output(output)]
    if len(image_positions) != len(keys):
        return False
    for offset, position in reversed(list(enumerate(image_positions))):
        expected = markers[offset] + "\n\n" + _caption_for(keys[offset]).strip()
        cleaned.insert(position + 1, _markdown_output(expected))
    _set(target, "outputs", cleaned)
    return True


def _ensure_interleaved_figure_captions(cells: MutableSequence) -> int:
    """Interleave captions for the two multi-image code cells by source meaning."""
    specs = [
        {
            "selector": lambda cell, src: (
                _is_code(cell)
                and "two_summary_file" in src
                and "finite_lung_profile.png" in src
            ),
            "items": [
                (
                    "display(NotebookImage(filename=str(two_dir / 'finite_lung_profile.png')))",
                    "fig-11-5-2-finite-lung-profile",
                    False,
                ),
                (
                    "display(NotebookImage(filename=str(two_dir / 'comparison.png')))",
                    "fig-11-5-3-finite-lung-comparison",
                    False,
                ),
            ],
        },
        {
            "selector": lambda cell, src: (
                _is_code(cell)
                and "old_legacy_curve.L_mm" in src
                and "cause_table" in src
                and "best_exact_residual" in src
            ),
            "items": [
                (
                    "            ax.set(title='Что воспроизводят восстановленные контактные функции',\n"
                    "                   xlabel='L, мм', ylabel='Z, Ом')\n"
                    "            ax.legend()",
                    "fig-14-1-contact-reconstruction",
                    True,
                ),
                (
                    "        axes[1].tick_params(axis='x', labelsize=8)",
                    "fig-14-2-cause-decomposition",
                    True,
                ),
                (
                    "    axes[1].set(title='Как читать остатки: нуль означает совпадение',\n"
                    "                xlabel='L, мм', ylabel='$Z_{модель}-Z_{эксперимент}$, Ом')\n"
                    "    axes[1].legend()",
                    "fig-14-3-current-historical-summary",
                    True,
                ),
            ],
        },
    ]

    changes = 0
    for spec in specs:
        target = _find_cell(cells, spec["selector"])
        if target is None:
            continue
        for anchor, key, display_figure in spec["items"]:
            if _inject_caption_after_source_line(
                target,
                anchor,
                key,
                display_figure=display_figure,
            ):
                changes += 1
        if _ensure_interleaved_outputs(
            cells,
            spec["selector"],
            [item[1] for item in spec["items"]],
        ):
            changes += 1
    return changes


def _ensure_anatomy_caption_output(cells: MutableSequence) -> bool:
    """Place the 3-D anatomy caption after fig3d, before the untouched phi plot."""
    target = _find_cell(cells, lambda cell, src: _is_code(cell) and "fig3d = go.Figure()" in src)
    if target is None:
        return False
    marker = _caption_marker("fig-3-1-historical-anatomy")
    caption = next(item["caption"] for item in CAPTION_CATALOG if item["key"] == "fig-3-1-historical-anatomy")
    output_caption = marker + "\n\n" + caption.strip()
    outputs = list(_get(target, "outputs", []) or [])
    for index, output in enumerate(outputs):
        if marker in _output_text(output):
            outputs[index] = _markdown_output(output_caption)
            _set(target, "outputs", outputs)
            return True
    for index, output in enumerate(outputs):
        text = _output_text(output)
        if all(token in text for token in ("лёгкие v3", "сердце", "кости")):
            outputs.insert(index + 1, _markdown_output(output_caption))
            _set(target, "outputs", outputs)
            return True
    # If the cell has not been executed, the source injection below will emit
    # the caption on the next run.  No orphan caption is inserted after phi.
    return False


def _inject_anatomy_caption_source(cells: MutableSequence) -> bool:
    target = _find_cell(cells, lambda cell, src: _is_code(cell) and "fig3d = go.Figure()" in src)
    if target is None:
        return False
    src = _source(target)
    marker = _caption_marker("fig-3-1-historical-anatomy")
    if marker in src:
        return False
    caption = next(item["caption"] for item in CAPTION_CATALOG if item["key"] == "fig-3-1-historical-anatomy")
    literal = json.dumps(marker + "\n\n" + caption.strip(), ensure_ascii=False)
    needle = "show_plotly(fig3d)"
    if needle not in src:
        return False
    _set_source(target, src.replace(needle, needle + "\n" + f"display(Markdown({literal}))", 1))
    return True


def _replace_source_fragment(cells: MutableSequence, selector: Callable[[object, str], bool], old: str, new: str) -> bool:
    target = _find_cell(cells, selector)
    if target is None:
        return False
    src = _source(target)
    if old not in src:
        return False
    _set_source(target, src.replace(old, new, 1))
    return True


def _replace_markdown_source(cells: MutableSequence, heading: str, old: str, new: str) -> bool:
    return _replace_source_fragment(
        cells,
        lambda cell, src: _is_markdown(cell) and heading in src,
        old,
        new,
    )


def _rewrite_section3(cells: MutableSequence) -> bool:
    target = _find_cell(
        cells,
        lambda cell, src: _is_markdown(cell) and src.startswith("## 3. Трёхмерная анатомия"),
    )
    if target is None:
        return False
    revised = r"""## 3. Трёхмерная анатомия и пространственное положение электродов

Объёмная сцена в этом разделе предназначена для проверки масштаба и взаимного положения наружной поверхности тела, внутренних областей и расчётных контактов. На ней показаны лёгкие, сердце, кости и центроиды 36 дискретных площадок девяти сборок; наличие объекта на сцене не означает, что ему во всех расчётах назначено отдельное удельное сопротивление.

Показанная сцена относится к историческому кандидату, использованному в разделах 1–10. Она не представляет текущую согласованную позу C01 раздела 20: центр и локальный базис C01 выбраны в отдельной части сохранённого перебора и отличаются от исторического результата. Поэтому рисунок следует использовать для чтения пространственной конфигурации старого расчёта, а не как независимую регистрацию фактической наклейки.

На сцене координатные оси $x$, $y$ и $z$ выражены в миллиметрах. Общая ось и центр относятся к параметризации исторической сборки; вспомогательная плоскость показывает направление локального геометрического анализа. Точный способ построения отображаемого сечения и ограничения его интерпретации описаны в разделе 4.

Следует различать заданный центр, его проекцию на наружную поверхность и центроид фактически выбранной площади. После дискретизации эти точки могут не совпасть. Электрический оператор CEM определяется полным набором узлов и граней контакта, поэтому совпадение центроидов ещё не доказывает тождество двух расчётов.

Угол ориентации измеряется в касательной плоскости выбранного поверхностного базиса. Он задаёт поворот общей оси модели; наклон каждой реальной установки, деформация сборки и ошибки четырёх взаимных расстояний здесь отдельными параметрами не восстанавливаются.
"""
    if _source(target) == revised:
        return False
    _set_source(target, revised)
    return True


def _apply_prose_edits(cells: MutableSequence) -> int:
    changes = 0

    old_abstract = (
        "**Текущее состояние исследования.** В [разделе 20](#saved-scan-study) изложен анализ 475 090 сохранённых FEM-поз: локализация сборки, визуализация электродов, проверка дискретного минимума и подбор общей толщины для девяти размеров. Лучший кандидат имеет RMSE 2,882 Ом; его соответствие фактической экспериментальной установке независимо не подтверждено. Полный перебор остаётся остановленным и незавершённым."
    )
    new_abstract = (
        "**Текущее состояние исследования.** В [разделе 20](#saved-scan-study) анализируется сохранённая часть многоразмерного перебора: 475 090 допустимых рассчитанных FEM-поз из 1 590 841 запрошенной позы. Обработаны 19 200 центров; 803 641 поза ещё не проверена. Минимум сохранённой части имеет RMSE 2,882 Ом и обозначен C01. Это дискретный численный кандидат при фиксированных сопротивлениях, а не независимо зарегистрированная фактическая установка; завершённость полного перебора и физическая валидация не установлены."
    )
    if _replace_markdown_source(cells, "# 20.10 Электрический импеданс", old_abstract, new_abstract):
        changes += 1

    if _rewrite_section3(cells):
        changes += 1

    inverse_intro_old = "## 7. Обратная задача и регуляризация\n\n### 7.1. Неизвестные параметры"
    inverse_intro_new = (
        "## 7. Обратная задача и регуляризация\n\n"
        "Прямая задача принимает геометрию, свойства тканей и токовый монтаж и выдаёт передаточный импеданс $Z(L)$. Обратная задача использует наблюдённые значения $Z(L)$, чтобы оценить неизвестные сопротивления и параметры позы внутри выбранной модели. Поэтому хорошее совпадение прямой кривой ещё не означает, что каждый параметр восстановлен однозначно: разные сочетания сопротивлений и геометрии могут давать близкий набор импедансов. Регуляризация выбирает область таких сочетаний с помощью дополнительных предпочтений; её влияние должно рассматриваться отдельно от остатка по измерениям.\n\n"
        "### 7.1. Неизвестные параметры"
    )
    if _replace_markdown_source(cells, "## 7. Обратная задача", inverse_intro_old, inverse_intro_new):
        changes += 1

    if _replace_markdown_source(
        cells,
        "## 7. Обратная задача",
        "В основном поиске сопротивления ограничены интервалами 2–10 и 10–32 Ом·м; геометрические диапазоны заданы в разделе 3.1. Это область допустимых параметров алгоритма.",
        "В основном поиске сопротивления ограничены интервалами 2–10 и 10–32 Ом·м; геометрические диапазоны заданы в разделе 3.1. Это прямоугольник допустимых параметров алгоритма, а не физиологический диапазон и не доверительный интервал. Значения, полученные на его границе или вне внешнего рабочего диапазона тканей, должны рассматриваться только как диагностические сценарии.",
    ):
        changes += 1

    section11_intro_old = "## 11. Аналитические представления и сопоставление прямых моделей\n\n### 11.1. Плоская двухслойная среда"
    section11_intro_new = (
        "## 11. Аналитические представления и сопоставление прямых моделей\n\n"
        "В этом разделе сравниваются две разные операции. Аналитическая модель заменяет пространственную анатомию идеализированной краевой задачей и поэтому уменьшает число геометрических переменных. Пространственная модель сохраняет кривые границы, конечные контакты и объёмное растекание тока, но требует решения объёмной краевой задачи. Сначала сравнение проводится при известных одинаковых сопротивлениях; только после этого обсуждается, как ошибка прямого приближения может повлиять на обратное восстановление параметров.\n\n"
        "### 11.1. Плоская двухслойная среда"
    )
    if _replace_markdown_source(cells, "## 11. Аналитические представления", section11_intro_old, section11_intro_new):
        changes += 1

    # The cleanup/geometry workers own the section-4 wording.  Only the
    # downstream definition in section 5 is clarified here.
    if _replace_markdown_source(
        cells,
        "## 5. Геометрические расстояния",
        "Профиль сечения аппроксимируется полиномом четвёртой степени по безразмерной координате:",
        "Профиль, полученный из выбранного сечения и используемый как диагностический вход редуцированной модели, аппроксимируется полиномом четвёртой степени по безразмерной координате:",
    ):
        changes += 1

    if _replace_markdown_source(
        cells,
        "## 9. Реестр допущений",
        "Для документированного кандидата сопротивления составляют приблизительно 5,552 и 30,707 Ом·м, RMS относительно эксперимента — 7,288 Ом. Эти значения используются как фиксированный вход двухтканного сравнения.",
        "Для документированного кандидата сопротивления составляют приблизительно 5,552 и 30,707 Ом·м, RMS относительно эксперимента — 7,288 Ом. Это условные оценки исходной четырёхтканной обратной задачи; они используются как фиксированный вход двухтканного сравнения и не считаются независимо измеренными физиологическими сопротивлениями.",
    ):
        changes += 1

    # Replace the old caption and explanation while preserving the numerical
    # result and the distinction between PEM and CEM.
    old_114 = (
        "**Рисунок 11.4а. Прямые расчёты пяти операторов для одного синтетического состояния.** Слева представлены импедансы, в центре — знаковые разности аналитических моделей с КТ/PEM, справа — соответствующие разности пространственных моделей. Раздельные вертикальные масштабы позволяют увидеть малые расхождения М3 и М4; их нельзя сравнивать по высоте линий без чтения осей. Близость к нулю означает лучшее воспроизведение референса в этом состоянии. Нулевая линия КТ является вычитанием результата из самого себя, а не нулевой физической погрешностью FEM.\n\n**Результат для этого состояния.** RMSE относительно КТ/PEM составляет 11,248 Ом для М1, 12,767 Ом для М2, 0,0540 Ом для М3 и 0,0405 Ом для М4. Переменная пространственная форма даёт наименьший RMSE среди кандидатов по девяти размерам, но не минимальную ошибку для каждого размера отдельно. При этом добавление профиля глубины в М2 ухудшило прямой прогноз относительно М1: больше геометрических сведений внутри эвристического усреднения не гарантирует более точного электрического поля.\n\nЭта проверка отвечает, насколько упрощение меняет импеданс при известных сопротивлениях. Она не устанавливает точность восстановления неизвестных $\\rho_1,\\rho_2$: для этого нужны независимые изменения обоих параметров и обратный расчёт 20.16. Площадки CEM проверяются отдельно при тех же заданных сопротивлениях; нельзя смешивать невязки относительно PEM и CEM или приписывать их только форме лёгкого. Новые варианты включения в полупространстве здесь ещё не рассчитаны."
    )
    new_114 = (
        _caption_marker("fig-11-4-direct-operators")
        + "\n\n"
        + next(
            item["caption"]
            for item in CAPTION_CATALOG
            if item["key"] == "fig-11-4-direct-operators"
        )
    )
    if _replace_source_fragment(
        cells,
        lambda cell, src: _is_markdown(cell) and old_114 in src,
        old_114,
        new_114,
    ):
        changes += 1

    if _replace_markdown_source(
        cells,
        "### 11.5. Историческое сравнение",
        "Этот исторический материал объясняет, как возникли проверяемые геометрические гипотезы. Количественные результаты разных положений не объединяются в один опыт.",
        "Этот исторический материал объясняет происхождение проверяемых геометрических гипотез и показывает чувствительность вывода к правилам построения контактов. Количественные результаты разных положений и версий кода не объединяются в один опыт и не используются как независимая валидация текущего кандидата.",
    ):
        changes += 1

    # Remove an English implementation label from a retained plot without
    # touching the separate PEM phi figure owned by another worker.
    if _replace_source_fragment(
        cells,
        lambda cell, src: _is_code(cell) and "weak_delta_z = J @ weak_physical" in src,
        "ylabel='s',\n           title='Спектр масштабированного finite-step Jacobian'",
        "ylabel='масштабированное сингулярное число, Ом',\n           title='Спектр масштабированных конечных секущих'",
    ):
        changes += 1

    if _replace_source_fragment(
        cells,
        lambda cell, src: _is_code(cell) and "volume_scenarios = pd.DataFrame" in src,
        "label='измеренное delta Z'",
        "label='измеренное ΔZ'",
    ):
        changes += 1
    if _replace_source_fragment(
        cells,
        lambda cell, src: _is_code(cell) and "volume_scenarios = pd.DataFrame" in src,
        "label=f'только delta rho2={delta_rho2_only:.1f} Ом·м'",
        "label=f'только Δρ₂={delta_rho2_only:.1f} Ом·м'",
    ):
        changes += 1
    if _replace_source_fragment(
        cells,
        lambda cell, src: _is_code(cell) and "volume_scenarios = pd.DataFrame" in src,
        "label=f'delta rho1={delta_rho12[0]:.2f}, delta rho2={delta_rho12[1]:.1f}'",
        "label=f'Δρ₁={delta_rho12[0]:.2f}, Δρ₂={delta_rho12[1]:.1f} Ом·м'",
    ):
        changes += 1

    # Reader-facing labels in the saved dynamic message; numbers remain byte
    # for byte identical apart from the wording around them.
    for cell in cells:
        if not _is_code(cell):
            continue
        src = _source(cell)
        if "two_summary_file" in src:
            if _replace_source_fragment(
                cells,
                lambda candidate, candidate_src: candidate is cell,
                "**Происхождение сравнения:** рабочий скрипт изменён после расчёта; "
                "его сохранённая версия проверена по исходной контрольной сумме. "
                "Эта проверка не является повторным расчётом.",
                "**Происхождение чисел.** Сохранена версия расчётного кода, применённая "
                "при получении этих результатов; её контрольная сумма проверена. "
                "Это проверка происхождения и не повторный расчёт.",
            ):
                changes += 1
            break

    return changes


def _apply_section20_caption_edits(cells: MutableSequence) -> int:
    replacements = [
        (
            "*Рисунок 20.1. Проекции результатов на параметрическую плоскость: а — минимум ошибки FEM относительно эксперимента по поворотам в каждом центре; б — минимум худшей ошибки в полностью рассчитанном допустимом окне из 125 поз при 25 различных проецируемых центрах; в — минимум ошибки двуслойного приближения FEM; г — минимум большей из двух ошибок, вычисленных в одной позе. Чем меньше ошибка, тем зеленее цвет; при 15 Ом цветовая шкала насыщается. Серый означает отсутствие пригодного значения соответствующего критерия и не равен нулевой ошибке. В интерактивной карте причины отсутствия результата показаны раздельно. На панелях могут выбираться разные повороты.*",
            "*Рисунок 20.1. Карты критериев на сохранённой параметрической сетке локализации. По координатам $u$ и $v$ показаны: а — минимум ошибки FEM относительно эксперимента по углу в каждом центре; б — минимум худшей ошибки в полностью рассчитанном окне 5×5×5; в — минимум ошибки двуслойного приближения для FEM-кривой; г — минимум большей из двух ошибок в одной и той же позе. Единицы $u$ и $v$ — мм, ошибки — Ом; для каждой панели цвет выбирает наилучший доступный угол. Чем меньше ошибка, тем зеленее цвет, а при 15 Ом шкала насыщается. Серый цвет означает отсутствие пригодного значения из-за геометрического отказа, маски или отсутствия расчёта и не равен нулевой ошибке. Карта описывает обработанную часть перебора и не доказывает минимум непрерывной позы. Следующая проверка — локальное дискретное окно и контроль исключённых размеров.*",
        ),
        (
            "*Рисунок 20.2. Выбранная сборка на индивидуальной поверхности тела: а — общий вид; б — локальная область для номинального размера 140 мм. Цветом показаны фактические треугольные площадки CEM: I+ и I− — токовые электроды, V+ и V− — электроды измерения напряжения. Ромбы обозначают центры площади. Изображены контакты сеточной модели; их форма не является фотографически восстановленной формой наклеенных электродов. Координаты заданы в миллиметрах исходной системы КТ/FEM.*",
            "*Рисунок 20.2. Пространственное положение электродных площадок в кандидате C01. На панели а показана вся индивидуальная поверхность тела и все сборки, на панели б — локальный фрагмент для $L=140$ мм. Цветом обозначены фактические треугольные площадки CEM: $I+$ и $I-$ — токовые, $V+$ и $V-$ — измерительные контакты; ромбы показывают их центры площади. Координаты $x$, $y$, $z$ заданы в мм исходной системы КТ/FEM. Изображены контакты численной модели, а не фотографически восстановленная наклейка; поэтому фигура подтверждает сохранённую геометрию расчёта, но не фактическую установку на теле. Следующая таблица даёт координаты и площади без визуального округления.*",
        ),
        (
            "*Рисунок 20.3. Сопоставление размерных зависимостей: а — эксперимент, FEM и двуслойная модель с общей подобранной толщиной; б — подписанные остатки FEM относительно эксперимента. Линии соединяют дискретные размеры и служат для чтения графика. Различия между записями и модельные ошибки не представлены доверительными интервалами, поскольку их распределение не установлено.*",
            "*Рисунок 20.3. Сопоставление размерных зависимостей в выбранной позе. На панели а по оси $L$ отложен номинальный размер сборки, мм, по оси $Z$ — импеданс, Ом; показаны эксперимент, FEM и двуслойная модель с одной общей подобранной толщиной. На панели б приведены остатки $Z_{\\rm FEM}-Z_{\\rm эксп}$ для каждого размера, поэтому знак показывает направление расхождения. Линии соединяют дискретные наблюдения и не задают непрерывную зависимость. Доверительные интервалы не строились: распределение ошибок и независимость последовательных записей не установлены.*",
        ),
        (
            "*Рисунок 20.4. Локальная структура ошибки: а — карта центров при фиксированном угле 14°; б–г — срезы по одному параметру при двух остальных фиксированных. Ромб отмечает выбранную позу. Серые ячейки и разрывы линий означают отсутствие допустимого FEM-значения. Соединение точек линией не доказывает вид функции между узлами сетки.*",
            "*Рисунок 20.4. Локальная структура дискретной ошибки вокруг C01. На панели а показана RMSE в плоскости $(u,v)$ при фиксированном $\\varphi=14^\\circ$; на панелях б–г приведены срезы при изменении одного параметра. Координаты $u$ и $v$ выражены в мм, угол — в градусах, ошибка — в Ом. Ромб отмечает C01, серые ячейки и разрывы линий — позы без пригодного FEM-значения. Рисунок подтверждает локальный минимум на узлах сохранённой сетки, но не форму функции между ними и не непрерывную точность координат.*",
        ),
        (
            "*Рисунок 20.5. Изменение выбранного центра и ошибка прогноза исключённого размера. Эта проверка характеризует чувствительность выбора к составу размерного ряда; девять повторов не являются независимыми экспериментами и не образуют статистическую оценку точности локализации.*",
            "*Рисунок 20.5. Устойчивость локализации при поочерёдном исключении размера. Для каждого исключённого $L$, мм, показаны смещение выбранного проецируемого центра, мм, и подписанная ошибка прогноза исключённого импеданса, Ом. Нулевое смещение не исключает изменения угла; девять повторов используют один и тот же набор последовательных записей и не являются независимыми экспериментами. Рисунок проверяет зависимость выбора от состава размерного ряда, но не даёт статистической оценки точности установки.*",
        ),
        (
            "*Рисунок 20.6. Сопоставление определений толщины: а — эффективная толщина и глубина первого входа в лёгкое по нормали; штриховая линия показывает равенство, цвет — число параметрических поз в ячейке диаграммы; б — распределение ошибки к FEM при подборе толщины и при подстановке глубины КТ на одном наборе поз. Частоты не означают число независимых наблюдений: разные повороты и совпадающие проекции повторно учитываются как элементы перебора. Панель б ограничена 50 Ом. Все значения обеих выборок входят в показанный диапазон.*",
            "*Рисунок 20.6. Сравнение эффективной и геометрической толщины. На панели а по обеим осям отложена толщина в мм: $h_{\\rm eff}$, найденная по электрическому критерию, и глубина первого входа в лёгкое по нормали КТ; штриховая линия обозначает равенство, цвет — число поз в ячейке. На панели б показаны распределения RMSE к FEM при подборе общей толщины и при прямой подстановке глубины КТ; ошибка выражена в омах, диапазон ограничен 50 Ом. Частоты относятся к элементам перебора, а не к независимым наблюдениям. Различие распределений показывает, что электрически эффективная толщина не может автоматически считаться анатомической; следующая задача — оценить её устойчивость и неопределённость отдельно от подгонки.*",
        ),
    ]
    changes = 0
    for old, new in replacements:
        for cell in cells:
            if _is_markdown(cell) and old in _source(cell):
                _set_source(cell, _source(cell).replace(old, new, 1))
                changes += 1
                break
    return changes


def apply(nb):
    """Apply the prose/caption revision to a notebook object and return it."""
    cells = _cells(nb)
    changes = _apply_prose_edits(cells)
    changes += _apply_section20_caption_edits(cells)

    selectors = {
        "fig-5-1-thickness-profile": lambda cell, src: _is_code(cell) and "h_fit_rmse =" in src,
        "fig-7-1-inverse-diagnostics": lambda cell, src: _is_code(cell) and "best_so_far = np.minimum.accumulate" in src,
        "fig-8-1-finite-secants": lambda cell, src: _is_code(cell) and "jacobian_column_norm * sensitivity.plausible_scale" in src,
        "fig-11-4-direct-operators": lambda cell, src: _is_code(cell) and src.strip() == "display_direct()",
        "fig-11-5-1-historical-fixed-depth": lambda cell, src: _is_code(cell) and "direct_error_table = pd.DataFrame" in src,
        "fig-11-5-2-finite-lung-profile": lambda cell, src: _is_code(cell) and "finite_lung_profile.png" in src,
        "fig-11-5-3-finite-lung-comparison": lambda cell, src: _is_code(cell) and "comparison.png" in src and "two_summary_file" in src,
        "fig-11-5-4-parameter-fit": lambda cell, src: _is_code(cell) and "Z_plain_free_fit =" in src,
        "fig-12-1-breath-and-contact-discretization": lambda cell, src: _is_code(cell) and "geometry_diagnostic = grids.copy()" in src,
        "fig-14-1-contact-reconstruction": lambda cell, src: _is_code(cell) and "old_legacy_curve.L_mm" in src and "cause_table" not in src,
        "fig-14-2-cause-decomposition": lambda cell, src: _is_code(cell) and "forward_change_rms" in src and "objective_labels" in src,
        "fig-14-3-current-historical-summary": lambda cell, src: _is_code(cell) and "best_exact_residual" in src and "cause_table" not in src,
        "fig-16-1-singular-spectrum": lambda cell, src: _is_code(cell) and "weak_delta_z = J @ weak_physical" in src,
        "fig-17-1-breathing-diagnostic": lambda cell, src: _is_code(cell) and "volume_scenarios = pd.DataFrame" in src,
    }
    changes += _remove_generated_caption_cells(
        cells,
        set(INTERLEAVED_CAPTION_KEYS) | {"fig-11-4-direct-operators"},
    )
    changes += _ensure_interleaved_figure_captions(cells)

    for item in CAPTION_CATALOG:
        key = item["key"]
        if key == "fig-3-1-historical-anatomy":
            if _inject_anatomy_caption_source(cells):
                changes += 1
            if _ensure_anatomy_caption_output(cells):
                changes += 1
            continue
        if key == "fig-11-4-direct-operators" or key in INTERLEAVED_CAPTION_KEYS:
            continue
        selector = selectors.get(key)
        if selector is None:
            continue
        if _ensure_caption_after(cells, selector, key, item["caption"]):
            changes += 1

    metadata = dict(_get(nb, "metadata", {}) or {})
    metadata[MARKER_PREFIX] = {
        "module_version": MODULE_VERSION,
        "caption_keys": [item["key"] for item in CAPTION_CATALOG],
        "excluded_sections": ["3.1", "4", "13"],
    }
    _set(nb, "metadata", metadata)
    return nb


__all__ = ["CAPTION_CATALOG", "MODULE_VERSION", "apply"]
